export type ArtistKey =
  | "Kanye West"
  | "Drake"
  | "Travis Scott"
  | "Frank Ocean"
  | "Daniel Caesar"
  | "The Weeknd"
  | "Bad Bunny";

export const ARTISTS: { name: ArtistKey; songs: string[] }[] = [
  {
    name: "Kanye West",
    songs: [
      "Runaway",
      "Stronger",
      "Power",
      "Gold Digger",
      "All of the Lights",
      "Heartless",
      "Jesus Walks",
      "Flashing Lights",
      "Bound 2",
      "Can't Tell Me Nothing",
      "Black Skinhead",
      "Ultralight Beam",
      "Through the Wire",
      "Devil in a New Dress",
      "Touch the Sky",
      "Father Stretch My Hands Pt. 1",
      "Famous",
      "Good Life",
      "Love Lockdown",
      "All Falls Down",
      "Monster",
      "Dark Fantasy",
      "Blood on the Leaves",
      "Waves",
      "Hey Mama",
      "Homecoming",
      "Diamonds from Sierra Leone",
      "Gorgeous",
      "Slow Jamz",
      "Champion",
      "New Slaves",
      "Street Lights",
      "Spaceship",
      "We Don't Care",
      "Family Business",
      "Saint Pablo",
      "Real Friends",
      "Welcome to Heartbreak",
      "Wolves",
      "FML",
      "Hell of a Life",
      "Lost in the World",
      "I Wonder",
      "Roses",
      "Late",
      "Get 'Em High",
      "School Spirit",
      "Two Words",
      "Ghost Town",
      "Violent Crimes",
      "Hurricane",
      "Jesus Lord",
      "Off the Grid",
      "Jail",
      "24",
      "Believe What I Say",
      "Praise God",
      "Moon",
      "Carnival",
      "Good Morning",
      "Robocop",
      "Amazing",
      "Paranoid",
      "Coldest Winter",
    ],
  },
  {
    name: "Drake",
    songs: [
      "Marvins Room",
      "Hotline Bling",
      "God's Plan",
      "Passionfruit",
      "Take Care",
      "Headlines",
      "Started From the Bottom",
      "Nonstop",
      "One Dance",
      "Energy",
      "Jungle",
      "Hold On, We're Going Home",
      "0 to 100 / The Catch Up",
      "Forever",
      "Best I Ever Had",
      "Over",
      "Find Your Love",
      "The Motto",
      "Worst Behavior",
      "Trophies",
      "Pound Cake / Paris Morton Music 2",
      "From Time",
      "Furthest Thing",
      "Too Much",
      "Know Yourself",
      "5AM in Toronto",
      "Crew Love",
      "Fancy",
      "Successful",
      "Fireworks",
      "Shot for Me",
      "Doing It Wrong",
      "Look What You've Done",
      "Practice",
      "The Ride",
      "Lord Knows",
      "HYFR (Hell Ya Fuckin' Right)",
      "Make Me Proud",
      "Cameras",
      "Controlla",
      "Feel No Ways",
      "Fake Love",
      "Child's Play",
      "Redemption",
      "Back to Back",
      "Charged Up",
      "Summer Sixteen",
      "Jumpman",
      "Big Rings",
      "Portland",
      "Free Smoke",
      "Sticky",
      "Nice for What",
      "In My Feelings",
      "Laugh Now Cry Later",
      "Toosie Slide",
      "Chicago Freestyle",
      "Teenage Fever",
      "Champagne Poetry",
      "First Person Shooter",
      "Rich Baby Daddy",
      "Nokia",
      "Gimme a Hug",
      "Views",
    ],
  },
  {
    name: "Travis Scott",
    songs: [
      "SICKO MODE",
      "goosebumps",
      "STARGAZING",
      "ANTIDOTE",
      "HIGHEST IN THE ROOM",
      "90210",
      "BUTTERFLY EFFECT",
      "FE!N",
      "CAROUSEL",
      "NO BYSTANDERS",
      "R.I.P. SCREW",
      "SKELETONS",
      "STOP TRYING TO BE GOD",
      "ASTROTHUNDER",
      "NC-17",
      "WAKE UP",
      "COFFEE BEAN",
      "MELTDOWN",
      "MY EYES",
      "HYAENA",
      "I KNOW ?",
      "TELEKINESIS",
      "MODERN JAM",
      "CIRCUS MAXIMUS",
      "3500",
      "Maria I'm Drunk",
      "Oh My Dis Side",
      "Pornography",
      "Wasted",
      "Nightcrawler",
      "Piss On Your Grave",
      "Impossible",
      "Apple Pie",
      "Pray 4 Love",
      "beibs in the trap",
      "through the late night",
      "way back",
      "coordinate",
      "first take",
      "sweet sweet",
      "wonderful",
      "Drugs You Should Try It",
      "Mamacita",
      "Upper Echelon",
      "Don't Play",
      "Quintana",
      "SDP Interlude",
      "Houstonfornication",
      "YOSEMITE",
      "Can't Say",
      "Who? What!",
      "THANK GOD",
      "TOPIA TWINS",
      "PARASAIL",
      "DELRESTO (ECHOES)",
      "LOST FOREVER",
      "K-POP",
      "GOD'S COUNTRY",
      "LOOOVE",
      "TIL FURTHER NOTICE",
      "GATTI",
      "OUT WEST",
      "WHAT TO DO?",
      "ESCAPE PLAN",
    ],
  },
  {
    name: "Frank Ocean",
    songs: [
      "Thinkin Bout You",
      "Pink + White",
      "Self Control",
      "Nights",
      "Ivy",
      "Pyramids",
      "Nikes",
      "White Ferrari",
      "Bad Religion",
      "Super Rich Kids",
      "Lost",
      "Solo",
      "Godspeed",
      "Sweet Life",
      "Pink Matter",
      "Seigfried",
      "Chanel",
      "Novacane",
      "Forrest Gump",
      "Crack Rock",
      "Sierra Leone",
      "Pilot Jones",
      "Skyline To",
      "Be Yourself",
      "Good Guy",
      "Solo (Reprise)",
      "Futura Free",
      "Close to You",
      "Swim Good",
      "Strawberry Swing",
      "We All Try",
      "Lovecrimes",
      "Songs for Women",
      "There Will Be Tears",
      "Dust",
      "Nature Feels",
      "American Wedding",
      "Soul Calibur",
      "Provider",
      "Biking",
      "Lens",
      "DHL",
      "In My Room",
      "Cayendo",
      "Dear April",
      "Moon River",
      "At Your Best (You Are Love)",
      "Slide On Me",
      "Wither",
      "Comme des Garçons",
      "U-N-I-T-Y",
      "Higgs",
      "Rushes",
      "Rushes To",
      "Florida",
      "Mine",
      "Wiseman (unreleased)",
      "Voodoo (unreleased)",
      "Orion (unreleased)",
      "Bedtime Stories (unreleased)",
      "Trouble (unreleased)",
      "Coral (ft. Bon Iver) (leaked)",
      "Spaceman (leaked demo)",
      "Memrise (unreleased)",
    ],
  },
  {
    name: "Daniel Caesar",
    songs: [
      "Best Part (ft. H.E.R.)",
      "Get You (ft. Kali Uchis)",
      "Japanese Denim",
      "Blessed",
      "Always",
      "Hold Me Down",
      "Superpowers",
      "Loose",
      "We Find Love",
      "Neu Roses (Transgressor's Song)",
      "Take Me Away (ft. Syd)",
      "Transform (ft. Charlotte Day Wilson)",
      "Freudian",
      "CYANIDE",
      "SUPERPOSITION (ft. John Mayer)",
      "LOVE AGAIN (ft. Brandy)",
      "ENTROPY",
      "FRONTAL LOBE MUZIK (ft. Pharrell Williams)",
      "OPEN UP",
      "RESTORE THE FEELING",
      "TOO DEEP TO TURN BACK",
      "ARE YOU OK?",
      "COMPLEXITIES",
      "Ocho Rios",
      "Valentina",
      "Toronto 2014",
      "Disillusioned",
      "Cool",
      "Vince Van Gogh",
      "Pain Is Inevitable",
      "Let Me Go",
      "Buyer's Remorse",
      "Unstoppable",
      "Shot My Baby",
      "Homiesexual (ft. Ty Dolla $ign)",
      "Do You Like Me?",
      "Rain Down (ft. Sampha)",
      "Moon (ft. Bon Iver)",
      "Have a Baby (With Me)",
      "Call on Me",
      "Who Knows",
      "Baby Blue (ft. Norwill Simmonds)",
      "Touching God (ft. Blood Orange & Yebba)",
      "No More Loving (On Women I Don't Love) (ft. 646YF4T)",
      "Root of All Evil",
      "Sign of the Times",
      "Emily's Song",
      "Sins of the Father (ft. Bon Iver)",
      "Peaches (Justin Bieber, ft. Daniel Caesar & Giveon)",
      "Please Do Not Lean (ft. BADBADNOTGOOD)",
      "Waiting in Vain",
      "CYANIDE Remix (ft. Koffee)",
      "Rearrange My World (w/ Rex Orange County)",
      "There's a Field (That's Only Yours) (w/ Rex Orange County)",
      "Won't Live Here",
      "Death & Taxes",
      "Streetcar",
      "Pseudo",
      "Violet",
      "We'll Always Have Paris",
      "Hold On",
      "Beauty & Essex (Free Nationals, ft. Daniel Caesar & UMO)",
      "Chevalier",
      "Birthday (unreleased)",
    ],
  },
  {
    name: "The Weeknd",
    songs: [
      "Blinding Lights",
      "Starboy",
      "The Hills",
      "Can't Feel My Face",
      "Often",
      "Earned It",
      "House of Balloons / Glass Table Girls",
      "Wicked Games",
      "The Morning",
      "High for This",
      "Save Your Tears",
      "Call Out My Name",
      "I Feel It Coming",
      "Die for You",
      "Heartless",
      "In Your Eyes",
      "Pray for Me (w/ Kendrick Lamar)",
      "Acquainted",
      "Reminder",
      "Tell Your Friends",
      "The Knowing",
      "Love Me Harder (w/ Ariana Grande)",
      "Party Monster",
      "Sidewalks",
      "Secrets",
      "Real Life",
      "As You Are",
      "The Birds Pt. 1",
      "The Birds Pt. 2",
      "Twenty Eight",
      "Initiation",
      "Wanderlust",
      "Belong to the World",
      "Kiss Land",
      "Live For (ft. Drake)",
      "Tears in the Rain",
      "Pretty",
      "Adaptation",
      "Loft Music",
      "Coming Down",
      "What You Need",
      "Gone",
      "Rolling Stone",
      "The Zone (ft. Drake)",
      "Lonely Star",
      "Outside",
      "São Paulo (ft. Anitta)",
      "XO / The Host",
      "Montreal",
      "Hardest to Love",
      "Try Me",
      "Privilege",
      "After Hours",
      "Snowchild",
      "Alone Again",
      "Too Late",
      "Open Hearts",
      "Scared to Live",
      "Faith",
      "Take My Breath",
      "Sacrifice",
      "Out of Time",
      "Less Than Zero",
      "Timeless (w/ Playboi Carti)",
    ],
  },
  {
    name: "Bad Bunny",
    songs: [
      "Tití Me Preguntó",
      "Yonaguni",
      "DÁKITI (w/ Jhayco)",
      "Me Porto Bonito (w/ Chencho Corleone)",
      "Callaíta",
      "Moscow Mule",
      "Vete",
      "Safaera (w/ Jowell & Randy, Ñengo Flow)",
      "La Difícil",
      "BAILE INoLVIDABLE",
      "Soy Peor",
      "Ojitos Lindos (w/ Bomba Estéreo)",
      "Yo Perreo Sola",
      "MIA (ft. Drake)",
      "Después de la Playa",
      "DtMF",
      "Efecto",
      "NUEVAYoL",
      "Estamos Bien",
      "La Canción (w/ J Balvin)",
      "Un x100to (w/ Grupo Frontera)",
      "Neverita",
      "La Romana (w/ El Alfa)",
      "200 MPH (w/ Diplo)",
      "Diles",
      "Amorfoda",
      "El Apagón",
      "Caro",
      "Tenemos Que Hablar",
      "Si Veo a Tu Mamá",
      "La Santa (w/ Daddy Yankee)",
      "25/8",
      "Booker T",
      "Bichiyal (w/ Yaviah)",
      "PERFuMITO NUEVO (w/ RaiNao)",
      "La Mudanza",
      "Pero Ya No",
      "Solo de Mí",
      "Otra Noche en Miami",
      "Where She Goes",
      "Mónaco",
      "EoO",
      "VeLDÁ (w/ Omar Courtz, Dei V)",
      "Mojabi Ghost (w/ Tainy)",
      "Está Cabrón Ser Yo",
      "Pitorro de Coco",
      "Acho PR (w/ Arcángel, De La Ghetto, Ñengo Flow)",
      "Voy a Llevarte pa PR",
      "Andrea (w/ Buscabulla)",
      "Como Antes",
      "Ignorantes (w/ Sech)",
      "Yo No Soy Celoso",
      "Hablamos Mañana",
      "El Clúb",
      "Cybertruck",
      "Una Velita",
      "Café con Ron (w/ Los Pleneros de la Cresta)",
      "Weltita (w/ Chuwi)",
      "Turista",
      "Bokete",
      "Lo Que Le Pasó a Hawaii",
      "Tarot (w/ Jhayco)",
      "Party (w/ Rauw Alejandro)",
      "Hoy Cobré",
    ],
  },
];

export function getArtist(name: string) {
  return ARTISTS.find((a) => a.name === name);
}
