export type ArtistKey = string;

export const ARTISTS: { name: ArtistKey; songs: string[] }[] = [
  {
    name: "Kanye West",
    songs: [
      "Runaway",
      "Stronger",
      "Power",
      "Gold Digger",
      "All of the Lights",
      "Heartless",
      "Jesus Walks",
      "Flashing Lights",
      "Bound 2",
      "Can't Tell Me Nothing",
      "Black Skinhead",
      "Ultralight Beam",
      "Through the Wire",
      "Devil in a New Dress",
      "Touch the Sky",
      "Father Stretch My Hands Pt. 1",
      "Famous",
      "Good Life",
      "Love Lockdown",
      "All Falls Down",
      "Monster",
      "Dark Fantasy",
      "Blood on the Leaves",
      "Waves",
      "Hey Mama",
      "Homecoming",
      "Diamonds from Sierra Leone",
      "Gorgeous",
      "Slow Jamz",
      "Champion",
      "New Slaves",
      "Street Lights",
      "Spaceship",
      "We Don't Care",
      "Family Business",
      "Saint Pablo",
      "Real Friends",
      "Welcome to Heartbreak",
      "Wolves",
      "FML",
      "Hell of a Life",
      "Lost in the World",
      "I Wonder",
      "Roses",
      "Late",
      "Get 'Em High",
      "School Spirit",
      "Two Words",
      "Ghost Town",
      "Violent Crimes",
      "Hurricane",
      "Jesus Lord",
      "Off the Grid",
      "Jail",
      "24",
      "Believe What I Say",
      "Praise God",
      "Moon",
      "Carnival",
      "Good Morning",
      "Robocop",
      "Amazing",
      "Paranoid",
      "Coldest Winter",
    ],
  },
  {
    name: "Drake",
    songs: [
      "Marvins Room",
      "Hotline Bling",
      "God's Plan",
      "Passionfruit",
      "Take Care",
      "Headlines",
      "Started From the Bottom",
      "Nonstop",
      "One Dance",
      "Energy",
      "Jungle",
      "Hold On, We're Going Home",
      "0 to 100 / The Catch Up",
      "Forever",
      "Best I Ever Had",
      "Over",
      "Find Your Love",
      "The Motto",
      "Worst Behavior",
      "Trophies",
      "Pound Cake / Paris Morton Music 2",
      "From Time",
      "Furthest Thing",
      "Too Much",
      "Know Yourself",
      "5AM in Toronto",
      "Crew Love",
      "Fancy",
      "Houstatlantavegas",
      "Fireworks",
      "Shot for Me",
      "Doing It Wrong",
      "Look What You've Done",
      "Practice",
      "The Ride",
      "Lord Knows",
      "HYFR (Hell Ya Fuckin' Right)",
      "Make Me Proud",
      "Cameras / Good Ones Go",
      "Controlla",
      "Feel No Ways",
      "Fake Love",
      "Child's Play",
      "9",
      "Back to Back",
      "Charged Up",
      "Summer Sixteen",
      "Jumpman",
      "Massive",
      "Portland",
      "Free Smoke",
      "Sticky",
      "Nice for What",
      "In My Feelings",
      "Not You Too",
      "Toosie Slide",
      "Chicago Freestyle",
      "Teenage Fever",
      "Champagne Poetry",
      "First Person Shooter",
      "Rich Baby Daddy",
      "Nokia",
      "Gimme a Hug",
      "Janice STFU",
    ],
  },
  {
    name: "Travis Scott",
    songs: [
      "SICKO MODE",
      "goosebumps",
      "STARGAZING",
      "ANTIDOTE",
      "HIGHEST IN THE ROOM",
      "90210",
      "BUTTERFLY EFFECT",
      "FE!N",
      "CAROUSEL",
      "NO BYSTANDERS",
      "R.I.P. SCREW",
      "SKELETONS",
      "STOP TRYING TO BE GOD",
      "ASTROTHUNDER",
      "NC-17",
      "WAKE UP",
      "COFFEE BEAN",
      "MELTDOWN",
      "MY EYES",
      "HYAENA",
      "I KNOW ?",
      "TELEKINESIS",
      "MODERN JAM",
      "CIRCUS MAXIMUS",
      "3500",
      "Maria I'm Drunk",
      "Oh My Dis Side",
      "Pornography",
      "Wasted",
      "Nightcrawler",
      "Piss On Your Grave",
      "Impossible",
      "Apple Pie",
      "Pray 4 Love",
      "beibs in the trap",
      "through the late night",
      "way back",
      "coordinate",
      "first take",
      "sweet sweet",
      "wonderful",
      "Drugs You Should Try It",
      "Mamacita",
      "Upper Echelon",
      "Don't Play",
      "Quintana",
      "SDP Interlude",
      "Houstonfornication",
      "YOSEMITE",
      "Can't Say",
      "Who? What!",
      "THANK GOD",
      "TOPIA TWINS",
      "PARASAIL",
      "DELRESTO (ECHOES)",
      "LOST FOREVER",
      "K-POP",
      "GOD'S COUNTRY",
      "LOOOVE",
      "TIL FURTHER NOTICE",
      "GATTI",
      "OUT WEST",
      "WHAT TO DO?",
      "ESCAPE PLAN",
    ],
  },
  {
    name: "Frank Ocean",
    songs: [
      "Thinkin Bout You",
      "Pink + White",
      "Self Control",
      "Nights",
      "Ivy",
      "Pyramids",
      "Nikes",
      "White Ferrari",
      "Bad Religion",
      "Super Rich Kids",
      "Lost",
      "Solo",
      "Godspeed",
      "Sweet Life",
      "Pink Matter",
      "Seigfried",
      "Chanel",
      "Novacane",
      "Forrest Gump",
      "Crack Rock",
      "Sierra Leone",
      "Pilot Jones",
      "Skyline To",
      "Be Yourself",
      "Good Guy",
      "Solo (Reprise)",
      "Futura Free",
      "Close to You",
      "Swim Good",
      "Strawberry Swing",
      "We All Try",
      "Lovecrimes",
      "Songs for Women",
      "There Will Be Tears",
      "Dust",
      "Nature Feels",
      "American Wedding",
      "Soul Calibur",
      "Provider",
      "Biking",
      "Lens",
      "DHL",
      "In My Room",
      "Cayendo",
      "Dear April",
      "Moon River",
      "At Your Best (You Are Love)",
      "Slide On Me",
      "Wither",
      "Comme des Garçons",
      "U-N-I-T-Y",
      "Higgs",
      "Rushes",
      "Rushes To",
      "Florida",
      "Mine",
      "Wiseman (unreleased)",
      "Voodoo (unreleased)",
      "Orion (unreleased)",
      "Bedtime Stories (unreleased)",
      "Trouble (unreleased)",
      "Coral (ft. Bon Iver) (leaked)",
      "Spaceman (leaked demo)",
      "Memrise (unreleased)",
    ],
  },
  {
    name: "Daniel Caesar",
    songs: [
      "Best Part (ft. H.E.R.)",
      "Get You (ft. Kali Uchis)",
      "Japanese Denim",
      "Blessed",
      "Always",
      "Hold Me Down",
      "Superpowers",
      "Loose",
      "We Find Love",
      "Neu Roses (Transgressor's Song)",
      "Take Me Away (ft. Syd)",
      "Transform (ft. Charlotte Day Wilson)",
      "Freudian",
      "CYANIDE",
      "SUPERPOSITION (ft. John Mayer)",
      "LOVE AGAIN (ft. Brandy)",
      "ENTROPY",
      "FRONTAL LOBE MUZIK (ft. Pharrell Williams)",
      "OPEN UP",
      "RESTORE THE FEELING",
      "TOO DEEP TO TURN BACK",
      "ARE YOU OK?",
      "COMPLEXITIES",
      "Ocho Rios",
      "Valentina",
      "Toronto 2014",
      "Disillusioned",
      "Cool",
      "Vince Van Gogh",
      "Pain Is Inevitable",
      "Let Me Go",
      "Buyer's Remorse",
      "Unstoppable",
      "Shot My Baby",
      "Homiesexual (ft. Ty Dolla $ign)",
      "Do You Like Me?",
      "Rain Down (ft. Sampha)",
      "Moon (ft. Bon Iver)",
      "Have a Baby (With Me)",
      "Call on Me",
      "Who Knows",
      "Baby Blue (ft. Norwill Simmonds)",
      "Touching God (ft. Blood Orange & Yebba)",
      "No More Loving (On Women I Don't Love) (ft. 646YF4T)",
      "Root of All Evil",
      "Sign of the Times",
      "Emily's Song",
      "Sins of the Father (ft. Bon Iver)",
      "Peaches (Justin Bieber, ft. Daniel Caesar & Giveon)",
      "Please Do Not Lean (ft. BADBADNOTGOOD)",
      "Waiting in Vain",
      "CYANIDE Remix (ft. Koffee)",
      "Rearrange My World (w/ Rex Orange County)",
      "There's a Field (That's Only Yours) (w/ Rex Orange County)",
      "Won't Live Here",
      "Death & Taxes",
      "Streetcar",
      "Pseudo",
      "Violet",
      "We'll Always Have Paris",
      "Hold On",
      "Beauty & Essex (Free Nationals, ft. Daniel Caesar & UMO)",
      "Chevalier",
      "Birthday (unreleased)",
    ],
  },
  {
    name: "The Weeknd",
    songs: [
      "Blinding Lights",
      "Starboy",
      "The Hills",
      "Can't Feel My Face",
      "Often",
      "Earned It",
      "House of Balloons / Glass Table Girls",
      "Wicked Games",
      "The Morning",
      "High for This",
      "Save Your Tears",
      "Call Out My Name",
      "I Feel It Coming",
      "Die for You",
      "Heartless",
      "In Your Eyes",
      "Pray for Me (w/ Kendrick Lamar)",
      "Acquainted",
      "Reminder",
      "Tell Your Friends",
      "The Knowing",
      "Love Me Harder (w/ Ariana Grande)",
      "Party Monster",
      "Sidewalks",
      "Secrets",
      "Real Life",
      "As You Are",
      "The Birds Pt. 1",
      "The Birds Pt. 2",
      "Twenty Eight",
      "Initiation",
      "Wanderlust",
      "Belong to the World",
      "Kiss Land",
      "Live For (ft. Drake)",
      "Tears in the Rain",
      "Pretty",
      "Adaptation",
      "Loft Music",
      "Coming Down",
      "What You Need",
      "Gone",
      "Rolling Stone",
      "The Zone (ft. Drake)",
      "Lonely Star",
      "Outside",
      "São Paulo (ft. Anitta)",
      "XO / The Host",
      "Montreal",
      "Hardest to Love",
      "Try Me",
      "Privilege",
      "After Hours",
      "Snowchild",
      "Alone Again",
      "Too Late",
      "Open Hearts",
      "Scared to Live",
      "Faith",
      "Take My Breath",
      "Sacrifice",
      "Out of Time",
      "Less Than Zero",
      "Timeless (w/ Playboi Carti)",
    ],
  },
  {
    name: "Bad Bunny",
    songs: [
      "Tití Me Preguntó",
      "Yonaguni",
      "DÁKITI (w/ Jhayco)",
      "Me Porto Bonito (w/ Chencho Corleone)",
      "Callaíta",
      "Moscow Mule",
      "Vete",
      "Safaera (w/ Jowell & Randy, Ñengo Flow)",
      "La Difícil",
      "BAILE INoLVIDABLE",
      "Soy Peor",
      "Ojitos Lindos (w/ Bomba Estéreo)",
      "Yo Perreo Sola",
      "MIA (ft. Drake)",
      "Después de la Playa",
      "DtMF",
      "Efecto",
      "NUEVAYoL",
      "Estamos Bien",
      "La Canción (w/ J Balvin)",
      "Un x100to (w/ Grupo Frontera)",
      "Neverita",
      "La Romana (w/ El Alfa)",
      "200 MPH (w/ Diplo)",
      "Diles",
      "Amorfoda",
      "El Apagón",
      "Caro",
      "Tenemos Que Hablar",
      "Si Veo a Tu Mamá",
      "La Santa (w/ Daddy Yankee)",
      "Mónaco",
    ],
  },
  {
    name: "Kendrick Lamar",
    songs: [
      "HUMBLE.",
      "Alright",
      "Money Trees",
      "Swimming Pools (Drank)",
      "King Kunta",
      "m.A.A.d city",
      "Bitch, Don't Kill My Vibe",
      "DNA.",
      "Not Like Us",
      "Backseat Freestyle",
      "The Art of Peer Pressure",
      "Sing About Me, I'm Dying of Thirst",
      "Poetic Justice",
      "Good Kid",
      "ELEMENT.",
      "LOYALTY.",
      "LOVE.",
      "All the Stars",
      "These Walls",
      "i",
      "The Blacker the Berry",
      "Wesley's Theory",
      "How Much a Dollar Cost",
      "u",
      "For Free? (Interlude)",
      "Institutionalized",
      "Hood Politics",
      "Complexion (A Zulu Love)",
      "Mortal Man",
      "FEAR.",
      "PRIDE.",
      "XXX.",
      "FEEL.",
      "DUCKWORTH.",
      "YAH.",
      "LUST.",
      "GOD.",
      "BLOOD.",
      "Euphoria",
      "meet the grahams",
      "6:16 in LA",
      "squabble up",
      "tv off",
      "luther",
      "wacced out murals",
      "reincarnated",
      "peekaboo",
      "man at the garden",
      "gnx",
      "dodger blue",
      "hey now",
      "gloria",
      "heart pt. 6",
      "Like That",
      "ADHD",
      "Cartoon & Cereal",
      "HiiiPoWeR",
      "Rigamortus",
      "The Recipe",
      "Count Me Out",
      "N95",
      "Father Time",
      "United in Grief",
      "Auntie Diaries",
    ],
  },
  {
    name: "SZA",
    songs: [
      "Kill Bill",
      "Snooze",
      "Good Days",
      "The Weekend",
      "Love Galore",
      "Drew Barrymore",
      "Broken Clocks",
      "Supermodel",
      "Nobody Gets Me",
      "Shirt",
      "Doves in the Wind",
      "Prom",
      "Garden (Say It Like Dat)",
      "Go Gina",
      "Normal Girl",
      "20 Something",
      "Anything",
      "Pretty Little Birds",
      "I Hate U",
      "Open Arms",
      "Special",
      "Blind",
      "Low",
      "Smoking on My Ex Pack",
      "Ghost in the Machine",
      "F2F",
      "SOS",
      "Seek & Destroy",
      "Love Language",
      "Gone Girl",
      "Used",
      "Notice Me",
      "Conceited",
      "Too Late",
      "Far",
      "Forgiveless",
      "Saturn",
      "Drive",
      "BMF",
      "30 for 30",
      "PSA",
      "Crybaby",
      "Joni",
      "Diamond Boy",
      "Another Life",
      "My Turn",
      "Scorsese Baby Daddy",
      "Chill Baby",
      "Get Behind Me",
      "What Do I Do",
      "Hit Different",
      "Power Is Power",
      "Babylon",
      "Childs Play",
      "Sweet November",
      "Julia",
      "Warm Winds",
      "Green Mile",
      "2AM",
      "Miles",
      "Tread Carefully",
      "The Other Side",
      "Kiss Me More",
      "Consideration",
    ],
  },
  {
    name: "Tyler, the Creator",
    songs: [
      "EARFQUAKE",
      "See You Again",
      "Yonkers",
      "NEW MAGIC WAND",
      "Who Dat Boy",
      "IFHY",
      "911 / Mr. Lonely",
      "Boredom",
      "WUSYANAME",
      "RUNNING OUT OF TIME",
      "ARE WE STILL FRIENDS?",
      "Sticky",
      "Noid",
      "GONE, GONE / THANK YOU",
      "I THINK",
      "Garden Shed",
      "SMUCKERS",
      "She",
      "PUPPET",
      "A BOY IS A GUN*",
      "Where This Flower Blooms",
      "Foreword",
      "November",
      "Glitter",
      "LEMONHEAD",
      "SWEET / I THOUGHT YOU WANTED TO DANCE",
      "MASSA",
      "CORSO",
      "LUMBERJACK",
      "HOT WIND BLOWS",
      "JUGGERNAUT",
      "RISE!",
      "St. Chroma",
      "Rah Tah Tah",
      "Darling, I",
      "Hey Jane",
      "Take Your Mask Off",
      "Like Him",
      "Thought I Was Dead",
      "Judge Judy",
      "Balloon",
      "Tomorrow",
      "I Killed You",
      "Big Poe",
      "Sugar on My Tongue",
      "Ring Ring Ring",
      "Sucka Free",
      "Mommanem",
      "Stop Playing With Me",
      "Don't Tap That Glass / Tweakin'",
      "Don't You Worry Baby",
      "Tamale",
      "Domo23",
      "Bimmer",
      "F**king Young / Perfect",
      "DEATHCAMP",
      "CHERRY BOMB",
      "Cowboy",
      "Awkward",
      "48",
      "Answer",
      "Pigs",
      "OKRA",
      "GROUP B",
    ],
  },
  {
    name: "Kid Cudi",
    songs: [
      "Day 'n' Nite",
      "Pursuit of Happiness",
      "Soundtrack 2 My Life",
      "Mr. Rager",
      "Erase Me",
      "Reborn",
      "Cudi Zone",
      "Up Up & Away",
      "Make Her Say",
      "Sky Might Fall",
      "Heart of a Lion (Kid Cudi Theme Music)",
      "Marijuana",
      "Mojo So Dope",
      "REVOFEV",
      "GHOST!",
      "Trapped in My Mind",
      "Don't Play This Song",
      "These Worries",
      "All Along",
      "Maniac",
      "Scott Mescudi vs. the World",
      "The End",
      "Enter Galactic (Love Connection, Pt. 1)",
      "My World",
      "Solo Dolo (Nightmare)",
      "Alive",
      "Just What I Am",
      "Immortal",
      "King Wizard",
      "Unfuckwittable",
      "Brothers",
      "Beez",
      "Cold Blooded",
      "Internal Bleeding",
      "Going to the Ceremony",
      "Satellite Flight",
      "Surfin'",
      "Frequency",
      "Baptized in Fire",
      "Feel the Love",
      "4th Dimension",
      "Fire",
      "Cudi Montage",
      "Kids See Ghosts",
      "Freeee (Ghost Town, Pt. 2)",
      "Tequila Shots",
      "She Knows This",
      "Heaven on Earth",
      "The Void",
      "Show Out",
      "Mr. Solo Dolo III",
      "Sad People",
      "Leader of the Delinquents",
      "Dive",
      "Damaged",
      "Lovin' Me",
      "Sept. 16",
      "Willing to Trust",
      "Angel",
      "Pillow Talk",
      "Ashin' Kusher",
      "Down & Out",
      "Confused!",
      "Do What I Want",
    ],
  },
  {
    name: "Playboi Carti",
    songs: [
      "Magnolia",
      "Sky",
      "Shoota",
      "Long Time (Intro)",
      "R.I.P.",
      "wokeuplikethis*",
      "Location",
      "Love Hurts",
      "dothatshit!",
      "New Tank",
      "Stop Breathing",
      "Rockstar Made",
      "Vamp Anthem",
      "Go2DaMoon",
      "Fell In Luv",
      "Poke It Out",
      "Right Now",
      "Lean 4 Real",
      "Slay3r",
      "ILoveUIHateU",
      "M3tamorphosis",
      "Place",
      "King Vamp",
      "Teen X",
      "Beno!",
      "JumpOutTheHouse",
      "No Sl33p",
      "Control",
      "Over",
      "Die4Guy",
      "New N3on",
      "Punk Monk",
      "On That Time",
      "Foreign",
      "Pull Up",
      "Home (KOD)",
      "Old Money",
      "Mileage",
      "Choppa Won't Miss",
      "No Time",
      "FlatBed Freestyle",
      "Middle of the Summer",
      "Top",
      "Kelly K",
      "Half & Half",
      "NO. 9",
      "Let It Go",
      "Other Shit",
      "Yah Mean",
      "POP OUT",
      "EVIL J0RDAN",
      "K POP",
      "CRUSH",
      "MOJO JOJO",
      "RATHER LIE",
      "BACKD00R",
      "FINE SHIT",
      "TOXIC",
      "CHARGE DEM HOES A FEE",
      "GOOD CREDIT",
      "WALK",
      "MUNYUN",
      "WAKE UP F1LTHY",
      "LIKE WEEZY",
    ],
  },
  {
    name: "Lil Uzi Vert",
    songs: [
      "XO TOUR Llif3",
      "Money Longer",
      "The Way Life Goes",
      "Just Wanna Rock",
      "20 Min",
      "You Was Right",
      "Do What I Want",
      "Sauce It Up",
      "Erase Your Social",
      "Neon Guts",
      "P2",
      "Baby Pluto",
      "Lo Mein",
      "Silly Watch",
      "Celebration Station",
      "Pop",
      "Prices",
      "Bean (Kobe)",
      "Wassup",
      "That Way",
      "Homecoming",
      "Bigger Than Life",
      "Sideline Watching (Hold Up)",
      "Ps & Qs",
      "7AM",
      "Money Mitch",
      "Of Course We Ghetto Flowers",
      "Canadian Goose",
      "Scott and Ramona",
      "Futsal Shuffle 2020",
      "Sasuke",
      "Endless Fashion",
      "Flooded the Face",
      "Aye",
      "CS",
      "Spaceship",
      "Suicide Doors",
      "Werewolf",
      "Patience",
      "Days Come and Go",
      "Demon High",
      "Chrome Heart Tags",
      "Nakamura",
      "Glock in My Purse",
      "Pluto to Mars",
      "Sanguine Paradise",
      "Free Uzi",
      "Strawberry Peels",
      "Lotus",
      "Venetia",
      "Urgency",
      "Bust Me",
      "How to Talk",
      "Dark Queen",
      "Luv Scars",
      "Amped",
      "Zoom",
      "Hectic",
      "Came Up",
      "Mama, I'm Sorry",
      "Heavy Metal",
      "All Alone",
      "x2",
      "Died and Came Back",
    ],
  },
  {
    name: "Lana Del Rey",
    songs: [
      "Video Games",
      "Summertime Sadness",
      "Born to Die",
      "Young and Beautiful",
      "Blue Jeans",
      "West Coast",
      "Off to the Races",
      "Ride",
      "Norman fucking Rockwell",
      "Venice Bitch",
      "Doin' Time",
      "Mariners Apartment Complex",
      "Cinnamon Girl",
      "The greatest",
      "National Anthem",
      "Cola",
      "Shades of Cool",
      "Brooklyn Baby",
      "Ultraviolence",
      "Pretty When You Cry",
      "Sad Girl",
      "Old Money",
      "Dark Paradise",
      "Million Dollar Man",
      "Gods & Monsters",
      "Diet Mountain Dew",
      "Radio",
      "Carmen",
      "This Is What Makes Us Girls",
      "Lust for Life",
      "Love",
      "White Mustang",
      "Get Free",
      "13 Beaches",
      "Cherry",
      "High by the Beach",
      "Music to Watch Boys To",
      "Honeymoon",
      "Terrence Loves You",
      "Salvatore",
      "Religion",
      "Freak",
      "Art Deco",
      "Hope Is a Dangerous Thing for a Woman Like Me to Have - but I Have It",
      "Fuck It I Love You",
      "Bartender",
      "The Next Best American Record",
      "How to Disappear",
      "California",
      "Love Song",
      "Chemtrails over the Country Club",
      "White Dress",
      "Tulsa Jesus Freak",
      "Wild at Heart",
      "Arcadia",
      "Blue Banisters",
      "A&W",
      "Did You Know That There's a Tunnel Under Ocean Blvd",
      "The Grants",
      "Margaret",
      "Let the Light In",
      "Henry, Come On",
      "Bluebird",
      "Yes to Heaven",
    ],
  },
  {
    name: "Billie Eilish",
    songs: [
      "bad guy",
      "Birds of a Feather",
      "Happier Than Ever",
      "when the party's over",
      "everything i wanted",
      "ocean eyes",
      "bury a friend",
      "lovely",
      "Wildflower",
      "What Was I Made For?",
      "Lunch",
      "you should see me in a crown",
      "Therefore I Am",
      "Your Power",
      "ilomilo",
      "NDA",
      "my future",
      "Chihiro",
      "Skinny",
      "The Greatest",
      "Bellyache",
      "idontwannabeyouanymore",
      "Copycat",
      "Party Favor",
      "Watch",
      "My Boy",
      "xanny",
      "wish you were gay",
      "all the good girls go to hell",
      "my strange addiction",
      "8",
      "listen before i go",
      "i love you",
      "goodbye",
      "!!!!!!!",
      "Getting Older",
      "I Didn't Change My Number",
      "Billie Bossa Nova",
      "Oxytocin",
      "GOLDWING",
      "Lost Cause",
      "Halley's Comet",
      "Everybody Dies",
      "OverHeated",
      "Male Fantasy",
      "Not My Responsibility",
      "L'Amour de Ma Vie",
      "The Diner",
      "Bittersuite",
      "Blue",
      "No Time to Die",
      "Guess",
      "Never Felt So Alone",
      "Six Feet Under",
      "Bored",
      "Come Out and Play",
      "Hostage",
      "&Burn",
      "when i was older",
      "TV",
      "The 30th",
      "Lo Vas a Olvidar",
      "bitches broken hearts",
      "Fingers Crossed",
    ],
  },
  {
    name: "Tame Impala",
    songs: [
      "The Less I Know the Better",
      "Let It Happen",
      "Feels Like We Only Go Backwards",
      "Elephant",
      "New Person, Same Old Mistakes",
      "Eventually",
      "Borderline",
      "Lost in Yesterday",
      "The Moment",
      "Why Won't They Talk to Me?",
      "'Cause I'm a Man",
      "Yes I'm Changing",
      "Apocalypse Dreams",
      "Mind Mischief",
      "Solitude Is Bliss",
      "Why Won't You Make Up Your Mind?",
      "Alter Ego",
      "Endors Toi",
      "It Is Not Meant to Be",
      "Lucidity",
      "Desire Be Desire Go",
      "Half Full Glass of Wine",
      "Expectation",
      "Runway, Houses, City, Clouds",
      "Nangs",
      "The Bold Arrow of Time",
      "Music to Walk Home By",
      "Keep on Lying",
      "Be Above It",
      "Posthumous Forgiveness",
      "Breathe Deeper",
      "Is It True",
      "Tomorrow's Dust",
      "On Track",
      "One More Year",
      "Instant Destiny",
      "It Might Be Time",
      "Patience",
      "Sundown Syndrome",
      "List of People (To Try and Forget About)",
      "Powerlines",
      "Taxi's Here",
      "Disciples",
      "Reality in Motion",
      "Love/Paranoia",
      "Past Life",
      "Gossip",
      "Sun's Coming Up",
      "Nothing That Has Happened So Far Has Been Anything We Could Control",
      "I Don't Really Mind",
      "Jeremy's Storm",
      "She Just Won't Believe Me",
      "Glimmer",
      "One More Hour",
      "Dracula",
      "Loser",
      "End of Summer",
      "My Old Ways",
      "Oblivion",
      "No Reply",
      "Not My World",
      "Piece of Heaven",
      "Obsolete",
      "Afterthought",
    ],
  },
  {
    name: "Beyoncé",
    songs: [
      "Crazy In Love",
      "Baby Boy",
      "Naughty Girl",
      "Me, Myself and I",
      "Check On It",
      "Déjà Vu",
      "Ring the Alarm",
      "Irreplaceable",
      "Upgrade U",
      "Beautiful Liar",
      "Get Me Bodied",
      "If I Were a Boy",
      "Single Ladies",
      "Halo",
      "Diva",
      "Ego",
      "Sweet Dreams",
      "Video Phone",
      "Run the World",
      "Best Thing I Never Had",
      "Countdown",
      "Love On Top",
      "Party",
      "Dance for You",
      "XO",
      "Drunk in Love",
      "Partition",
      "Pretty Hurts",
      "Flawless",
      "Mine",
      "Jealous",
      "7/11",
      "Formation",
      "Sorry",
      "Hold Up",
      "Freedom",
      "Daddy Lessons",
      "All Night",
      "Don't Hurt Yourself",
      "Cuff It",
      "Break My Soul",
      "Alien Superstar",
      "Virgo's Groove",
      "Heated",
      "Pure/Honey",
      "Summer Renaissance",
      "Texas Hold 'Em",
      "16 Carriages",
      "Bodyguard",
      "Jolene",
      "Daughter",
      "Spaghettii",
      "Alligator Tears",
      "Just For Fun",
      "II Most Wanted",
      "Levii's Jeans",
      "Flamenco",
      "Ya Ya",
      "Desert Eagle",
      "Riiverdance",
      "II Hands II Heaven",
      "Tyrant",
      "Sweet Honey Buckiin'",
      "Ameriican Requiem",
    ],
  },
  {
    name: "Rihanna",
    songs: [
      "Pon de Replay",
      "If It's Lovin' That You Want",
      "SOS",
      "Unfaithful",
      "Break It Off",
      "We Ride",
      "Umbrella",
      "Shut Up and Drive",
      "Don't Stop the Music",
      "Hate That I Love You",
      "Take a Bow",
      "Disturbia",
      "Rehab",
      "Russian Roulette",
      "Hard",
      "Rude Boy",
      "Rockstar 101",
      "Te Amo",
      "Only Girl",
      "What's My Name",
      "S&M",
      "California King Bed",
      "Man Down",
      "Cheers",
      "We Found Love",
      "You Da One",
      "Where Have You Been",
      "Talk That Talk",
      "Cockiness",
      "Diamonds",
      "Stay",
      "Pour It Up",
      "Right Now",
      "What Now",
      "Jump",
      "FourFiveSeconds",
      "Bitch Better Have My Money",
      "American Oxygen",
      "Work",
      "Kiss It Better",
      "Needed Me",
      "Love on the Brain",
      "Sex With Me",
      "Consideration",
      "Desperado",
      "Higher",
      "Close to You",
      "Loveeeeeee Song",
      "Skin",
      "Fire Bomb",
      "Cold Case Love",
      "Photographs",
      "Fading",
      "Birthday Cake",
      "Nobody's Business",
      "Farewell",
      "Lift Me Up",
      "Lift Me Up (Instrumental)",
      "Dancing in the Dark",
      "Towards the Sun",
      "Believe It",
      "Lemon",
      "This Is What You Came For",
      "Princess of China",
    ],
  },
  {
    name: "A$AP Rocky",
    songs: [
      "Peso",
      "Purple Swag",
      "Goldie",
      "PMW",
      "F**kin' Problems",
      "Wild for the Night",
      "Fashion Killa",
      "LVL",
      "Angels",
      "Everyday",
      "L$D",
      "Jukebox Joints",
      "Excuse Me",
      "Electric Body",
      "Canal St.",
      "Fine Whine",
      "Praise the Lord",
      "A$AP Forever",
      "Tony Tone",
      "Buck Shots",
      "Kids Turned Out Fine",
      "Riot",
      "Same Problems?",
      "Tailor Swif",
      "Highjack",
      "Ruby Rosary",
      "Order Of Protection",
      "Helicopter",
      "Stole Ya Flow",
      "Stay Here 4 Life",
      "No Trespassing",
      "Punk Rocky",
    ],
  },
  {
    name: "ROSALÍA",
    songs: [
      "Catalina",
      "De Plata",
      "Aunque Es De Noche",
      "Malamente",
      "Pienso En Tu Mirá",
      "Di Mi Nombre",
      "Bagdad",
      "De Aquí No Sales",
      "Reniego",
      "A Ningún Hombre",
      "Con Altura",
      "Yo x Ti, Tu x Mi",
      "Juro Que",
      "Dolerme",
      "La Fama",
      "Saoko",
      "Candy",
      "La Combi Versace",
      "Chicken Teriyaki",
      "Hentai",
      "Bizcochito",
      "G3 N15",
      "Motomami",
      "Diablo",
      "Delirio de Grandeza",
      "Cuuuuuuuuuute",
      "Despechá",
      "Vampiros",
      "Beso",
      "LLYLM",
      "Tuya",
      "Omega",
    ],
  },
  {
    name: "Steve Lacy",
    songs: [
      // Gemini Rights (2022)
      "Bad Habit",
      "Mercury",
      "Sunshine",
      "Static",
      "Helmet",
      "Buttons",
      "Give You the World",
      "Amber",
      "2Gether (The Birds)",
      "Last 2 Gether",
      // The Lo-Fis (2020)
      "Out of Me Head",
      "Donchano (Don't Worry 'Bout Me)",
      "Cody Freestyle",
      "Infrunami",
      "Some",
      "Cocky Girl",
      "Heavy",
      "Jean",
      "Looks",
      "C U Girl",
      "Bars.16",
      "When I'm With You",
      // Apollo XXI (2019)
      "Only If",
      "Like Me",
      "Playground",
      "Basement Jack",
      "Hate CD",
      "Lay Me Down",
      "In Lust We Trust",
      "Amandla's Interlude",
      "N Side",
      "Love 2 Fast",
    ],
  },
  {
    name: "Yung Lean",
    songs: [
      "Ginseng Strip 2002",
      "Kyoto",
      "Hurt",
      "Yoshi City",
      "Oreomilkshake",
      "Lightsaber // Saviour",
      "Volt",
      "Miami Ultras",
      "Hoover",
      "Afghanistan",
      "Red Bottom Sky",
      "Agony",
      "Yellowman",
      "Highway Patrol",
      "Hennessy & Sailor Moon",
      "Eye Contact",
      "Pikachu",
      "Boylife in EU",
      "Violence",
      "My Agenda",
      "Outta My Head",
      "Bliss",
      "Starz",
      "Trip",
      "SummerTime Blood",
      "Happy Feet",
      "Nobody Else",
      "Metal Storm",
      "Forever Yung",
      "Ghosts",
      "Babyface Maniacs",
      "Wooden Girl",
    ],
  },
  {
    name: "BROCKHAMPTON",
    songs: [
      "SUGAR",
      "ZIPPER",
      "BLEACH",
      "WEIGHT",
      "NO HALO",
      "QUEER",
      "GOLD",
      "BUZZCUT",
      "BERLIN",
      "SWEET",
      "HEAT",
      "STAR",
      "NEW ORLEANS",
      "BOOGIE",
      "JELLO",
      "JUNKY",
      "J'OUVERT",
      "SAN MARCOS",
      "GUMMY",
      "SWIM",
      "IF YOU PRAY RIGHT",
      "CHAIN ON",
      "BOY BYE",
      "DEARLY DEPARTED",
      "JOHNNY",
      "ALASKA",
      "COUNT ME IN",
      "BANKROLL",
      "BUMP",
      "TEETH",
      "FACE",
      "TOKYO",
      "TRIP",
      "GAMBA",
      "DIRT",
      "LIQUID",
      "STAINS",
      "TONYA",
      "THUG LIFE",
      "FABRIC",
      "VIVID DREAM",
      "WHERE THE CASH AT",
      "DISTRICT",
      "HONEY",
      "THE LIGHT",
      "WHAT'S THE OCCASION?",
      "WHEN I BALL",
      "FEEL SOMETHING",
      "ACTING BRAND NEW",
      "PRESSURE",
      "EXTERNAL",
      "LEONARD",
      "DON'T SHOOT UP THE PARTY",
      "BROCKHAMPTON",
      "SUPERSTAR",
      "THE FAMILY (IT'S A MOVIE)",
      "FORMAT",
      "MCDONALD'S",
      "HELMET",
      "FM",
      "THE ENDING",
      "DANDELION",
      "DEAR LORD",
      "LOVE ME FOR LIFE",
    ],
  },
  {
    name: "Charli XCX",
    songs: [
      "360",
      "Good Ones",
      "Boom Clap",
      "Break the Rules",
      "Von Dutch",
      "Apple",
      "1999",
      "White Mercedes",
      "Used to Know Me",
      "Beg for You",
      "Girl, so confusing",
      "Sympathy is a knife",
      "I Think About It All the Time",
      "Speed Drive",
      "Gone",
      "Vroom Vroom",
      "Party 4 U",
      "Claws",
      "Next Level Charli",
      "Pink Diamond",
      "B2b",
      "Forever",
      "Mean girls",
      "Club classics",
      "Talk talk",
      "So I",
      "Anthems",
      "Everything is romantic",
      "Rewind",
      "365",
      "New Shapes",
      "Crash",
      "Detonate",
      "Lightning",
      "Twice",
      "Constant Repeat",
      "Yuck!",
      "Moving",
      "Every Rule",
      "Baby",
      "Cross You Out",
      "February 2017",
      "Click",
      "I Don't Wanna Know",
      "Thoughts",
      "Official",
      "Trophy",
      "Backseat",
      "ILY2",
      "Lucky",
      "Out of My Head",
      "Emotional",
      "Delicious",
      "Track 10",
      "Tears",
      "Unlock It",
      "5 in the Morning",
      "Boys",
      "I Got It",
      "House",
      "Chains of Love",
      "Wall of Sound",
      "Rock Music",
      "SS26",
    ],
  },
  {
    name: "Taylor Swift",
    songs: [
      "Anti-Hero",
      "Shake It Off",
      "Blank Space",
      "Love Story",
      "You Belong with Me",
      "Cruel Summer",
      "All Too Well (10 Minute Version)",
      "Style",
      "Wildest Dreams",
      "cardigan",
      "august",
      "willow",
      "champagne problems",
      "exile",
      "Fearless",
      "We Are Never Ever Getting Back Together",
      "I Knew You Were Trouble",
      "22",
      "Bad Blood",
      "Don't Blame Me",
      "Delicate",
      "Getaway Car",
      "New Romantics",
      "Clean",
      "Out of the Woods",
      "How You Get the Girl",
      "Enchanted",
      "Back to December",
      "Should've Said No",
      "The Archer",
      "Lover",
      "Death by a Thousand Cuts",
      "seven",
      "illicit affairs",
      "this is me trying",
      "evermore",
      "marjorie",
      "tolerate it",
      "no body no crime",
      "nothing new",
      "Midnight Rain",
      "Bejeweled",
      "Lavender Haze",
      "Maroon",
      "Snow on the Beach",
      "Mastermind",
      "Would've, Could've, Should've",
      "Dear John",
      "15",
      "the 1",
      "epiphany",
      "long live",
      "Change",
      "The Last Great American Dynasty",
      "Treacherous",
      "I Almost Do",
      "Come Back...Be Here",
      "The Tortured Poets Department",
      "The Smallest Man Who Ever Lived",
      "But Daddy I Love Him",
      "Fortnight",
      "The Fate of Ophelia",
      "Opalite",
      "Elizabeth Taylor",
    ],
  },
  {
    name: "Bon Iver",
    songs: [
      "Holocene",
      "Skinny Love",
      "Towers",
      "Re: Stacks",
      "Calgary",
      "Flume",
      "Minnesota, WI",
      "Perth",
      "Blood Bank",
      "For Emma",
      "Michicant",
      "Lump Sum",
      "715 - CR∑∑KS",
      "22 (OVER S∞∞N)",
      "33 \"GOD\"",
      "Hey, Ma",
      "Creature Fear",
      "Salem",
      "Naeem",
      "Marion",
      "Faith",
      "8 (circle)",
      "29 #Strafford APTS",
      "00000 Million",
      "Blindsided",
      "Woods",
      "Wash.",
      "Beth/Rest",
      "S P E Y S I D E",
      "Everything Is Peaceful Love",
      "If Only I Could Wait",
      "I'll Be There",
    ],
  },
  {
    name: "Coldplay",
    songs: [
      "The Scientist",
      "Fix You",
      "Clocks",
      "Yellow",
      "Viva la Vida",
      "Sparks",
      "Speed of Sound",
      "The Hardest Part",
      "In My Place",
      "God Put a Smile upon Your Face",
      "Warning Sign",
      "Amsterdam",
      "Shiver",
      "Trouble",
      "A Sky Full of Stars",
      "Magic",
      "Paradise",
      "Every Teardrop Is a Waterfall",
      "Princess of China",
      "Charlie Brown",
      "Us Against the World",
      "Atlas",
      "Midnight",
      "A Head Full of Dreams",
      "Hymn for the Weekend",
      "Adventure of a Lifetime",
      "My Universe",
      "Higher Power",
      "feelslikeimfallinginlove",
      "We Pray",
      "All My Love",
      "GOOD FEELiNGS",
    ],
  },
  {
    name: "Radiohead",
    songs: [
      "Karma Police",
      "Creep",
      "Paranoid Android",
      "No Surprises",
      "Fake Plastic Trees",
      "Everything in Its Right Place",
      "Idioteque",
      "Weird Fishes/Arpeggi",
      "Exit Music (For a Film)",
      "Let Down",
      "How to Disappear Completely",
      "Pyramid Song",
      "Street Spirit (Fade Out)",
      "There There",
      "Reckoner",
      "Just",
      "High and Dry",
      "Nude",
      "Jigsaw Falling into Place",
      "15 Step",
      "Lotus Flower",
      "Burn the Witch",
      "Airbag",
      "The National Anthem",
      "All I Need",
      "Bodysnatchers",
      "2+2=5",
      "Lucky",
      "My Iron Lung",
      "Planet Telex",
      "The Bends",
      "Climbing Up the Walls",
    ],
  },
  {
    name: "Mac Miller",
    songs: [
      "Self Care",
      "Small Worlds",
      "Good News",
      "Dang!",
      "Come Back to Earth",
      "Blue World",
      "What's the Use?",
      "2009",
      "Circles",
      "Objects in the Mirror",
      "Diablo",
      "100 Grandkids",
      "Brand Name",
      "Ladders",
      "Dunno",
      "Programs",
      "Wings",
      "So It Goes",
      "Hand Me Downs",
      "Surf",
      "Everybody",
      "Once a Day",
      "Right",
      "Hurt Feelings",
      "Conversation Pt. 1",
      "Aquarium",
      "Jet Fuel",
      "Perfecto",
      "Complicated",
      "That's on Me",
      "God Is Fair, Sexy Nasty",
      "Stay",
      "Cinderella",
      "Perfect Circle / God Speed",
      "Weekend",
      "In the Bag",
      "Clubhouse",
      "Grand Finale",
      "Funeral",
      "The Question",
      "Lucky Me",
      "Soulmate",
      "God Speed",
      "Goosebumpz",
      "Someone Like You",
      "I Am Who Am (Killin' Time)",
      "Rain",
      "Zest",
      "We",
      "Inside Outside",
      "Skin",
      "Planet God Damn",
      "Ascension",
      "Two Matches",
      "ROS",
      "Nikes on My Feet",
      "Star Room",
      "Donald Trump",
      "Knock Knock",
      "Party on Fifth Ave.",
      "Break the Law",
      "Suplexes Inside of Complexes and Misdirected Furies",
      "New Faces",
      "REMember",
    ],
  },
  {
    name: "J. Cole",
    songs: [
      "Love Yourz",
      "No Role Modelz",
      "Apparently",
      "Middle Child",
      "G.O.M.D.",
      "A Tale of 2 Citiez",
      "Crooked Smile",
      "Power Trip",
      "Fire Squad",
      "Note to Self",
      "Let Nas Down",
      "Born Sinner",
      "She Knows",
      "03 Adolescence",
      "Lost Ones",
      "Work Out",
      "Return of Simba",
      "KOD",
      "ATM",
      "FRIENDS",
      "Once an Addict",
      "Kevin's Heart",
      "Photograph",
      "Window Pain",
      "Forbidden Fruit",
      "Land of the Snakes",
      "Chaining Day",
      "St. Tropez",
      "Ville Mentality",
      "Immortal",
      "Neighbors",
      "Change",
      "4 Your Eyez Only",
      "Dollar and a Dream III",
      "Sideline Story",
      "Cole Summer",
      "Be Careful",
      "BRACKETS",
      "amari",
      "punchin' the clock",
      "my.life",
      "Pride.is.the.Devil",
      "let go my hand",
      "apply pressure",
      "1 0 9",
      "January 28th",
      "Dreams",
      "Nobody's Perfect",
      "In the Morning",
      "Deja Vu",
      "The Climb Back",
      "Clouds",
      "Who TF Iz U",
      "Two Six",
      "Safety",
      "Poor Thang",
      "Legacy",
      "Bunce Road Blues",
      "29 Intro",
      "Bombs in the Ville / Hit the Gas",
      "The Let Out",
      "The Fall-Off Is Inevitable",
      "Losing My Balance",
      "Dollar and a Dream II",
    ],
  },
  {
    name: "Brent Faiyaz",
    songs: [
      "Trust",
      "Clouded",
      "Dead Man Walking",
      "Wasting Time",
      "Gravity",
      "ROLE MODEL",
      "Rehab (Winter in Paris)",
      "ALL MINE",
      "POISONED APPLE",
      "Stay Down",
      "Been Away",
      "Show U Off",
      "Lost Me",
      "Flyin' Out",
      "Loose Change",
      "Rolling Stone",
      "Ghetto Gatsby",
      "Bigger Man",
      "Price of Fame",
      "Dark Saint",
      "Angel",
      "Must Go",
      "First World Problems",
      "They Don't Know",
      "butterflies",
      "WY@",
      "No One Knows",
      "Be Careful",
      "Smoke One",
      "Talk 2 U",
      "Have To",
      "Tony Soprano",
      "Peter Pan",
      "Full Moon (Fall in Tokyo)",
    ],
  },
  {
    name: "Jhené Aiko",
    songs: [
      "The Worst",
      "While We're Young",
      "None of Your Concern",
      "Triggered (Freestyle)",
      "Sativa",
      "Bed Peace",
      "Spotless Mind",
      "To Love & Die",
      "B.S.",
      "Happiness Over Everything (H.O.E.)",
      "Pussy Fairy (OTW)",
      "Tryna Love U",
      "In My Head",
      "One Way St.",
      "Stay Ready (What a Life)",
      "Eternal Sunshine",
      "Magic Hour",
      "Promises to Myself",
      "Maniac",
      "Comfort Inn Ending (Freestyle)",
      "Wrap Me Up",
      "W.A.Y.S.",
      "Summer 2020",
      "Higher",
      "Speak",
      "Surrender",
      "Never Call Me",
      "Frequency",
      "Krishnas",
      "Born Tired",
      "Lyin King",
      "The Pressure",
      "guidance",
      "Break",
    ],
  },
  {
    name: "Childish Gambino",
    songs: [
      "Redbone",
      "This Is America",
      "3005",
      "Feels Like Summer",
      "Sober",
      "Heartbeat",
      "Bonfire",
      "Summertime Magic",
      "Me and Your Mama",
      "Sweatpants",
      "Have Some Love",
      "Telegraph Ave.",
      "Zealots of Stockholm (Free Information)",
      "The Worst Guys",
      "Riot",
      "Boogieman",
      "Stand Tall",
      "Terrified",
      "California",
      "Zombies",
      "Worldstar",
      "Urn",
      "Baby Boy",
      "Time",
      "Little Foot Big Foot",
      "Algorhythm",
      "Why Go to the Party",
      "Lithonia",
      "Freaks and Geeks",
      "Fire Fly",
      "Outside",
      "Kids (Keep Up)",
      "Hold You Down",
      "All the Shine",
      "Letter Home",
      "L.E.S.",
      "That Power",
      "Life: The Biggest Troll",
      "Pink Toes",
      "The Crawl",
      "Shadows",
      "Flight of the Navigator",
      "Backpackers",
      "Sunrise",
      "Sweet Thang",
      "Human Sacrifice",
      "Final Church",
      "Atavista",
      "Real Love",
      "We Are God",
      "Got to Be",
      "In the Night",
      "Survive",
      "Yoshinoya",
      "A Place Where Love Goes",
      "Pop Thieves (Make It Feel Good)",
      "Retro (Rough)",
      "The Palisades",
      "Late Night in Kauai",
      "The Night Me and Your Mama Met",
      "Death by Numbers",
      "Toxic",
      "American Royalty",
      "Psilocyderum",
    ],
  },
  {
    name: "Future",
    songs: [
      "Mask Off",
      "Life Is Good",
      "March Madness",
      "Jumpman",
      "Like That",
      "Turn On the Lights",
      "Move That Dope",
      "Codeine Crazy",
      "Low Life",
      "Where Ya At",
      "Used to This",
      "Stick Talk",
      "Fuck Up Some Commas",
      "Wicked",
      "Thought It Was a Drought",
      "Same Damn Time",
      "Honest",
      "Karate Chop",
      "Tony Montana",
      "Sh!t",
      "Real Sisters",
      "Throw Away",
      "I Serve the Base",
      "Blood on the Money",
      "Freak Hoe",
      "Draco",
      "Crushed Up",
      "Jersey",
      "Never Stop",
      "Rich $ex",
      "Incredible",
      "PuffinOnZootiez",
      "WAIT FOR U",
      "Love You Better",
      "Type Shit",
      "Cinderella",
      "Magic I Want It",
      "Hardly",
      "Plastic",
      "Solo",
      "Posted with Demons",
      "Last Breath",
      "My Collection",
      "Selfish",
      "Comin Out Strong",
      "Diamonds Dancing",
      "Scholarships",
      "Big Rings",
      "Perkys Calling",
      "News or Somthn",
      "Trap N****s",
      "Lookin Exotic",
      "The Percocet & Stripper Joint",
      "Xanny Family",
      "Maybach",
      "Slave Master",
      "Use Me",
      "When I Was Broke",
      "Group Home",
      "56 Nights",
      "Wifi Lit",
      "Rich N****a Shit",
      "Keep It Burnin",
      "Hate the Real Me",
    ],
  },
  {
    name: "Giveon",
    songs: [
      "Heartbreak Anniversary",
      "Like I Want You",
      "For Tonight",
      "Lie Again",
      "Lost Me",
      "Still Your Best",
      "World We Created",
      "Stuck on You",
      "Favorite Mistake",
      "All to Me",
      "November",
      "Vanish",
      "The Beach",
      "Scarred",
      "For the Night",
      "Another Lifetime",
      "One Way",
      "Hold On",
      "Ugly",
      "When It's All Said and Done",
      "SAVE SOME FOR ME",
      "Twenties",
      "Rather Be",
      "Fade",
      "This Time Around",
      "Last Time",
      "Whole Situation",
      "For What It's Worth",
      "Worth It",
      "Never Let Me Go",
      "Spiritual",
      "The Other Side",
    ],
  },
  {
    name: "Lil Wayne",
    songs: [
      "A Milli",
      "Lollipop",
      "6 Foot 7 Foot",
      "Uproar",
      "How to Love",
      "Mirror",
      "Mrs. Officer",
      "Got Money",
      "3 Peat",
      "She Will",
      "Right Above It",
      "Dr. Carter",
      "Phone Home",
      "Let the Beat Build",
      "Tie My Hands",
      "Mona Lisa",
      "Don't Cry",
      "Dark Side of the Moon",
      "Go DJ",
      "Fireman",
      "Stuntin' Like My Daddy",
      "Comfortable",
      "Shoot Me Down",
      "Playing with Fire",
      "Mr. President",
      "Famous",
      "Dedicate",
      "Let It All Work Out",
      "John",
      "Nightmares of the Bottom",
      "La La La",
      "Every Girl",
      "Took His Time",
      "Glory",
      "Start This Sh** Off Right",
      "Open Letter",
      "Mess",
      "Used 2",
      "Wayne on Me",
      "Problems",
      "Grove St. Party",
      "Mahogany",
      "I Do It",
      "Piano Trap",
      "Receipt",
      "Funeral",
      "I'm Good",
      "Hittas",
      "Demon",
      "Kant Nobody",
      "Carter Boys",
      "Mr. Carter",
      "Weezy Baby",
      "Blunt Blowin'",
      "Rich as F**k",
      "I'm Goin' In",
      "Gonorrhea",
      "Duffle Bag Boy",
      "Prom Queen",
      "Richer Than I've Ever Been",
      "Tha Carter",
      "What About Me",
      "Ice Melts",
      "Feel Me",
    ],
  },
  {
    name: "Juice WRLD",
    songs: [
      "Lucid Dreams",
      "All Girls Are the Same",
      "Robbery",
      "Wishing Well",
      "Righteous",
      "Legends",
      "Smile",
      "Come & Go",
      "Conversations",
      "Hate the Other Side",
      "Bad Energy",
      "Life's a Mess",
      "Man of the Year",
      "Armed & Dangerous",
      "Lean wit Me",
      "Fast",
      "Black & White",
      "Ring Ring",
      "Burn",
      "Already Dead",
      "Feeling",
      "Hide",
      "Titanic",
      "Heard It All Before",
      "Doom",
      "Wandered to LA",
      "Up Up & Away",
      "End of the Road",
      "Anxiety",
      "Used to",
      "Fine China",
      "No, You Don't",
      "Syphilis",
      "Flaws and Sins",
      "ZAZA",
      "Rider",
      "HeMotions",
      "Maze",
      "Screw Juice",
      "Side Effects",
      "Cigarettes",
      "Real Damage",
      "My Dark Thoughts",
      "Rockstar in His Prime",
      "Feeling Alone",
      "Let Me Know",
      "Can't Die",
      "Run",
      "Bad Vibes Forever",
      "Lace It",
      "Floor It",
      "Party by Myself",
      "AGATS2 (Insecure)",
      "Best Friend",
      "Empty Out Your Pockets",
      "In My Head",
      "Doomsday",
      "Candles",
      "Hear Me Calling",
      "Stay High",
      "Shooter",
      "Into Your Arms",
      "Nobody",
      "The Way",
    ],
  },
  {
    name: "Central Cee",
    songs: [
      "Doja",
      "Commitment Issues",
      "Sprinter",
      "Band4Band",
      "Loading",
      "Retail Therapy",
      "Cold Shoulder",
      "Khabib",
      "GBP",
      "Truth in the Lies",
      "CRG",
      "Which One",
      "Gen Z Luv",
      "Iceman Freestyle",
      "Slaughter",
      "Wagwan",
      "Booga",
      "One by One",
      "CC Freestyle",
      "Did It First",
      "6 for 6",
      "Obsessed with You",
      "No Nuts",
      "Plead the 5th",
      "Streatham",
      "Can't Say I Didn't Try",
      "Trapstar",
      "Pinging (6 Figures)",
      "Day in the Life",
      "Guilt Trippin",
      "Loud",
      "Strip",
    ],
  },
  {
    name: "Joji",
    songs: [
      "Will He",
      "Demons",
      "Window",
      "Yeah Right",
      "No Fun",
      "Once in a While",
      "I Don't Wanna Waste My Time",
      "XNXX",
      "Reanimator",
      "PIXELATED KISSES",
      "SLOW DANCING IN THE DARK",
      "TEST DRIVE",
      "ATTENTION",
      "CAN'T GET OVER YOU",
      "WHY AM I STILL IN LA",
      "R.I.P.",
      "I'll See You in 40",
      "Ew",
      "Sanctuary",
      "Run",
      "Upgrade",
      "Pretty Boy",
      "Gimme Love",
      "Daylight",
      "Afterthought",
      "Tick Tock",
      "Like You Do",
      "Glimpse of Us",
      "Die For You",
      "NIGHT RIDER",
      "1AM FREESTYLE",
      "777",
    ],
  },
  {
    name: "Post Malone",
    songs: [
      "Circles",
      "Sunflower",
      "Rockstar",
      "Congratulations",
      "White Iverson",
      "I Fall Apart",
      "Better Now",
      "Psycho",
      "Wow.",
      "Goodbyes",
      "Take What You Want",
      "Hollywood's Bleeding",
      "Saint-Tropez",
      "Die for Me",
      "On the Road",
      "Enemies",
      "Staring at the Sun",
      "Myself",
      "A Thousand Bad Times",
      "Go Flex",
      "Deja Vu",
      "Cold",
      "Stay",
      "Same Bitches",
      "Sugar Wraith",
      "Candy Paint",
      "Paranoid",
      "Feeling Whitney",
      "Broken Whiskey Glass",
      "Motley Crew",
      "I Like You (A Happier Song)",
      "I Had Some Help",
    ],
  },
  {
    name: "Phoebe Bridgers",
    songs: [
      "Motion Sickness",
      "Kyoto",
      "Garden Song",
      "Punisher",
      "Moon Song",
      "I Know the End",
      "Chinese Satellite",
      "ICU",
      "Halloween",
      "Savior Complex",
      "Scott Street",
      "Funeral",
      "Smoke Signals",
      "Graceland Too",
      "Sidelines",
      "Demi Moore",
      "Killer",
      "Would You Rather",
      "Georgia",
      "Chelsea",
      "You Missed My Heart",
      "Steamroller",
      "So Much Wine",
      "If We Make It Through December",
      "7 O'Clock News / Silent Night",
      "Day After Tomorrow",
      "Christmas Song",
      "Have Yourself a Merry Little Christmas",
      "Iris",
      "Friday I'm in Love",
      "That Funny Feeling",
      "Waiting Room",
    ],
  },
  {
    name: "Bryson Tiller",
    songs: [
      "Don't",
      "Exchange",
      "Sorry Not Sorry",
      "Right My Wrongs",
      "Open Interlude",
      "502 Come Up",
      "Been That Way",
      "The Sequence",
      "Self-Made",
      "End of the Road",
      "Pen Griffey",
      "Run Me Dry",
      "Somethin Tells Me",
      "You Got It",
      "Honey",
      "Get Mine",
      "Stay Blessed",
      "Set It Off",
      "In Check",
      "Things Change",
      "We Both Know",
      "Like Clockwork",
      "Foreplay",
      "Inhale",
      "Less of You",
      "Outta Time",
      "Ciao!",
      "Whoa",
      "Whatever She Wants",
      "Steady Bouncin",
      "Always Forever",
      "Rambo",
    ],
  },
  {
    name: "Bruno Mars",
    songs: [
      "Just the Way You Are",
      "Grenade",
      "Locked Out of Heaven",
      "When I Was Your Man",
      "Uptown Funk",
      "24K Magic",
      "Treasure",
      "Marry You",
      "The Lazy Song",
      "Talking to the Moon",
      "Count on Me",
      "Versace on the Floor",
      "That's What I Like",
      "Finesse",
      "Chunky",
      "Perm",
      "Calling All My Lovelies",
      "Straight Up & Down",
      "Too Good to Say Goodbye",
      "Liquor Store Blues",
      "Runaway Baby",
      "Our First Time",
      "The Other Side",
      "Young Girls",
      "Gorilla",
      "Moonshine",
      "Leave the Door Open",
      "Smokin Out the Window",
      "Skate",
      "Apt.",
      "Die With a Smile",
      "Billionaire",
    ],
  },
  {
    name: "Eminem",
    songs: [
      "Lose Yourself",
      "Without Me",
      "Stan",
      "The Real Slim Shady",
      "My Name Is",
      "Not Afraid",
      "Love the Way You Lie",
      "Rap God",
      "Mockingbird",
      "Sing for the Moment",
      "Cleanin' Out My Closet",
      "When I'm Gone",
      "Like Toy Soldiers",
      "Beautiful",
      "Berzerk",
      "Survival",
      "Headlights",
      "Space Bound",
      "The Way I Am",
      "Forgot About Dre",
      "Guilty Conscience",
      "Just Lose It",
      "Mosh",
      "Encore",
      "Killshot",
      "Venom",
      "Walk on Water",
      "River",
      "Phenomenal",
      "Legacy",
      "Bad Guy",
      "Renegade",
      "No Love",
      "So Bad",
      "25 to Life",
      "Cinderella Man",
      "Won't Back Down",
      "W.T.P.",
      "Going Through Changes",
      "Bad Husband",
      "Stepping Stone",
      "Untouchable",
      "Fall",
      "Lucky You",
      "The Ringer",
      "Greatest",
      "Premonition",
      "Godzilla",
      "Darkness",
      "Marsh",
      "Tone Deaf",
      "Gnat",
      "Higher",
      "Black Magic",
      "Houdini",
      "Tobey",
      "Temporary",
      "'Till I Collapse",
      "Soldier",
      "White America",
      "Square Dance",
      "Hailie's Song",
      "Drug Ballad",
      "Brain Damage",
    ],
  },
  {
    name: "Young Thug",
    songs: [
      "Best Friend",
      "Stoner",
      "Lifestyle",
      "Check",
      "Pick Up the Phone",
      "Hot",
      "The London",
      "Wyclef Jean",
      "Constantly Hating",
      "Memo",
      "Digits",
      "Power",
      "Halftime",
      "Harambe",
      "Floyd Mayweather",
      "Surf",
      "Family Don't Matter",
      "Hi-Tek",
      "Givenchy",
      "Just How It Is",
      "Bad Bad Bad",
      "Ecstasy",
      "RiRi",
      "With Them",
      "Webbie",
      "F Cancer",
      "Big Tipper",
      "Tick Tock",
      "Climax",
      "That's All",
      "Anybody",
      "Killed Before",
    ],
  },
  {
    name: "Olivia Rodrigo",
    songs: [
      "drivers license",
      "good 4 u",
      "deja vu",
      "vampire",
      "bad idea right?",
      "all-american bitch",
      "lacy",
      "ballad of a homeschooled girl",
      "making the bed",
      "logical",
      "get him back!",
      "love is embarrassing",
      "the grudge",
      "pretty isn't pretty",
      "teenage dream",
      "brutal",
      "traitor",
      "1 step forward, 3 steps back",
      "enough for you",
      "happier",
      "jealousy, jealousy",
      "favorite crime",
      "hope ur ok",
      "obsessed",
      "so american",
      "stranger",
      "scared of my guitar",
      "girl i've always been",
      "can't catch me now",
      "all i want",
      "out of the old",
      "butterflies",
    ],
  },
  {
    name: "Dominic Fike",
    songs: [
      "3 Nights",
      "Phone Numbers",
      "She Wants My Money",
      "King of Everything",
      "Açaí Bowl",
      "Westcoast Collective",
      "Joe Blazey",
      "Why",
      "Babydoll",
      "Politics & Violence",
      "10x Stronger",
      "Cancel Me",
      "Chicken Tenders",
      "Vampire",
      "Come Here",
      "Sumo",
      "What Could I Do",
      "Frisky",
      "Mama's Boy",
      "Mona Lisa",
      "Ant Pile",
      "How Much Is Weed?",
      "Dancing in the Courthouse",
      "Both",
      "Elliot's Song",
      "Wurli",
      "Florida",
      "Don't Stare at the Sun",
      "Bodies",
      "Susan",
      "Pasture Child",
      "Think Fast",
    ],
  },
  {
    name: "FKA twigs",
    songs: [
      "Two Weeks",
      "Cellophane",
      "Lights On",
      "Pendulum",
      "Hours",
      "Video Girl",
      "Numbers",
      "Closer",
      "Kicks",
      "Give Up",
      "thousand eyes",
      "home with you",
      "sad day",
      "holy terrain",
      "mary magdalene",
      "fallen alien",
      "mirrored heart",
      "daybed",
      "ride the dragon",
      "tears in the club",
      "honda",
      "meta angel",
      "oh my love",
      "jealousy",
      "papi bones",
      "darjeeling",
      "careless",
      "Striptease",
      "lightbeams",
      "Eusexua",
      "Perfect Stranger",
      "Drums of Death",
    ],
  },
  {
    name: "Don Toliver",
    songs: [
      "No Idea",
      "After Party",
      "Cardigan",
      "Lemonade",
      "Drugs N Hella Melodies",
      "Lockdown",
      "Spaceship",
      "Company",
      "Cigarettes",
      "Backend",
      "5x",
      "Way Bigger",
      "Outerspace",
      "Cinderella",
      "Bus Stop",
      "Smoke",
      "What You Need",
      "Embarrassed",
      "Genesis",
      "Slow Motion",
      "Crocodile Teeth",
      "Honeymoon",
      "Pop Out",
      "Best You Had",
      "Inside Lookin Out",
      "Bandit",
      "Private Landing",
      "Get Throwed",
      "Leave The Club",
      "Hardstone Psycho",
      "Brand New",
      "Time Heals All",
    ],
  },
  {
    name: "Mitski",
    songs: [
      "Nobody",
      "Washing Machine Heart",
      "My Love Mine All Mine",
      "Your Best American Girl",
      "First Love / Late Spring",
      "Francis Forever",
      "I Bet on Losing Dogs",
      "Last Words of a Shooting Star",
      "A Burning Hill",
      "Drunk Walk Home",
      "Class of 2013",
      "Townie",
      "Geyser",
      "Why Didn't You Stop Me?",
      "Pink in the Night",
      "Lonesome Love",
      "Remember My Name",
      "Me and My Husband",
      "A Pearl",
      "Two Slow Dancers",
      "Once More to See You",
      "Working for the Knife",
      "The Only Heartbreaker",
      "Love Me More",
      "Heat Lightning",
      "Stay Soft",
      "Should've Been Me",
      "Bug Like an Angel",
      "Buffalo Replaced",
      "Heaven",
      "The Deal",
      "When Memories Snow",
    ],
  },
  {
    name: "XXXTENTACION",
    songs: [
      "SAD!",
      "Jocelyn Flores",
      "Moonlight",
      "Look at Me!",
      "Hope",
      "Changes",
      "Fuck Love",
      "King",
      "Numb",
      "Garette's Revenge",
      "Everybody Dies in Their Nightmares",
      "Revenge",
      "Depression & Obsession",
      "Save Me",
      "Carry On",
      "The Remedy for a Broken Heart",
      "Pain = BESTFRIEND",
      "infinity (888)",
      "Going Down!",
      "Schizophrenia",
      "I Spoke to the Devil in Miami",
      "Whoa (Mind in Awe)",
      "ALONE, PART 3",
      "STARING AT THE SKY",
      "BAD!",
      "Falling Down",
      "Arms Around You",
      "Hearteater",
      "Vice City",
      "Limbo",
      "School Shooters",
      "Riot",
    ],
  },
  {
    name: "Justin Bieber",
    songs: [
      "Baby",
      "Sorry",
      "Love Yourself",
      "What Do You Mean?",
      "Despacito",
      "Where Are Ü Now",
      "Cold Water",
      "Peaches",
      "Holy",
      "Anyone",
      "Stay",
      "Ghost",
      "Honest",
      "Lonely",
      "Hold On",
      "Yummy",
      "Intentions",
      "10,000 Hours",
      "I'm the One",
      "Beauty and a Beat",
      "Boyfriend",
      "As Long As You Love Me",
      "Mistletoe",
      "One Time",
      "Eenie Meenie",
      "Somebody to Love",
      "Pray",
      "Never Say Never",
      "All Around the World",
      "Confident",
      "Heartbreaker",
      "All That Matters",
      "Believe",
      "As I Am",
      "Available",
      "Off My Face",
      "Deserve You",
      "Somebody",
      "Habitual",
      "Love You Different",
      "Unstable",
      "Name",
      "Don't Go",
      "Friends",
      "Common Denominator",
      "Backpack",
      "Insecurities",
      "Take You",
      "Right Here",
      "Bad Day",
      "Company",
      "Children",
      "Mark My Words",
      "No Pressure",
      "The Feeling",
      "Daisies",
      "Yukon",
      "Devotion",
      "Sweet Spots",
      "Butterflies",
      "Walking Away",
      "Things You Do",
      "Dadz Love",
      "Swag",
    ],
  },
  {
    name: "Sufjan Stevens",
    songs: [
      "Mystery of Love",
      "Visions of Gideon",
      "Should Have Known Better",
      "Death with Dignity",
      "Fourth of July",
      "John My Beloved",
      "Carrie & Lowell",
      "Eugene",
      "All of Me Wants All of You",
      "No Shade in the Shadow of the Cross",
      "Blue Bucket of Gold",
      "Drawn to the Blood",
      "Chicago",
      "Casimir Pulaski Day",
      "John Wayne Gacy, Jr.",
      "Predatory Wasp of the Palisades Is Out to Get Us!",
      "Illinois",
      "Come On! Feel the Illinoise!",
      "Jacksonville",
      "Decatur",
      "The Tallest Man, the Broadest Shoulders",
      "Futile Devices",
      "Impossible Soul",
      "Age of Adz",
      "I Walked",
      "Too Much",
      "Vesuvius",
      "Sister",
      "All Delighted People",
      "Tonya Harding",
      "Will Anybody Ever Love Me?",
      "So You Are Tired",
    ],
  },
  {
    name: "Aminé",
    songs: [
      "Caroline",
      "Spice Girl",
      "Heebiejeebies (feat. Kehlani)",
      "Wedding Crashers",
      "Turf",
      "Dakota",
      "Money",
      "Veggies",
      "Sundays",
      "Yellow",
      "REEL IT IN",
      "BLACKJACK",
      "DR. WHOEVER",
      "SHINE",
      "RATCHET SATURN GIRL",
      "Vacay",
      "Compensating (feat. Young Thug)",
      "Shimmy",
      "Pressure in My Palms (feat. slowthai & Vince Staples)",
      "Burden",
      "Woodlawn",
      "Mama",
      "Fetus",
      "Can't Decide",
      "Roots",
      "Riri",
      "Kobe",
      "Charmander",
      "Mad Funny Freestyle",
      "OKWME",
      "Colors",
      "4EVA",
    ],
  },
  {
    name: "Lorde",
    songs: [
      "Royals",
      "Green Light",
      "Team",
      "Tennis Court",
      "Ribs",
      "400 Lux",
      "Liability",
      "Perfect Places",
      "Supercut",
      "Sober",
      "Homemade Dynamite",
      "The Louvre",
      "Hard Feelings / Loveless",
      "Writer in the Dark",
      "Solar Power",
      "Mood Ring",
      "Stoned at the Nail Salon",
      "Fallen Fruit",
      "Secrets from a Girl (Who's Seen It All)",
      "Oceanic Feeling",
      "Buzzcut Season",
      "A World Alone",
      "White Teeth Teens",
      "Glory and Gore",
      "Still Sane",
      "Magnets",
      "What Was That",
      "Man of the Year",
      "Shapeshifter",
      "Hammer",
      "Broken Glass",
      "Bravado",
    ],
  },
  {
    name: "Kali Uchis",
    songs: [
      "telepatía",
      "Moonlight",
      "After the Storm",
      "I Wish You Roses",
      "Dead to Me",
      "Just a Stranger",
      "Tyrant",
      "Solita",
      "Tu Bebito",
      "fue mejor",
      "que te pedi",
      "labios mordidos",
      "no hay ley parte 2",
      "Igual Que un Ángel",
      "Endlessly",
      "Get Together",
      "Tomorrow",
      "Hasta Cuando",
      "Te Pongo Mal",
      "Sin Miedo",
      "aguardiente y limón",
      "ángel sin cielo",
      "All Mine",
      "Loner",
      "Know What I Want",
      "Body Language",
      "Worth the Wait",
      "Ridin Round",
      "Coming Home",
      "Stay High",
      "Heaven Is a Home",
      "Muñekita",
    ],
  },
  {
    name: "Kaytranada",
    songs: [
      "Glowed Up",
      "Lite Spots",
      "10%",
      "Got It Good",
      "You're the One",
      "Drive Me Crazy",
      "Weight Off",
      "Bus Ride",
      "Together",
      "Vivid Dreams",
      "Track Uno",
      "Despite the Weather",
      "Need It",
      "Look Easy",
      "Vex Oh",
      "Culture",
      "Taste",
      "Gray Area",
      "Oh No",
      "Worst in Me",
      "Midsection",
      "Twin Flame",
      "Stuntin",
      "Snap My Finger",
      "Witchy",
      "Wasis Diop",
      "Lover/Friend",
      "Pressure",
      "More Than a Little Bit",
      "Skin",
      "Hold On",
      "Feel a Way",
    ],
  },
  {
    name: "Dua Lipa",
    songs: [
      "New Rules",
      "Don't Start Now",
      "Levitating",
      "Houdini",
      "Physical",
      "One Kiss",
      "IDGAF",
      "Be the One",
      "Hotter Than Hell",
      "Blow Your Mind",
      "Cold Heart",
      "Electricity",
      "Sweetest Pie",
      "Dance the Night",
      "Training Season",
      "Illusion",
      "These Walls",
      "French Exit",
      "Falling Forever",
      "Anything for Love",
      "End of an Era",
      "Maria",
      "Watcha Doing",
      "Love Again",
      "Hallucinate",
      "Pretty Please",
      "Cool",
      "Future Nostalgia",
      "Break My Heart",
      "Good in Bed",
      "Boys Will Be Boys",
      "Lost in Your Light",
    ],
  },
  {
    name: "ENHYPEN",
    songs: [
      "Given-Taken",
      "Let Me In",
      "10 Months",
      "Drunk-Dazed",
      "Fever",
      "Not For Sale",
      "Mixed Up",
      "Tamed-Dashed",
      "Go Big or Go Home",
      "Upper Side Dreamin'",
      "Blessed-Cursed",
      "Polaroid Love",
      "Attention, please!",
      "Future Perfect",
      "Shout Out",
      "ParadoXXX Invasion",
      "Bite Me",
      "Sacrifice",
      "Chaconne",
      "Bills",
      "Criminal Love",
      "Sweet Venom",
      "Still Monster",
      "Orange Flower",
      "Blind",
      "Moonstruck",
      "Brought The Heat Back",
      "XO",
      "Paranormal",
      "Daydream",
      "No Doubt",
      "Loose",
    ],
  },
  {
    name: "LE SSERAFIM",
    songs: [
      "ANTIFRAGILE",
      "UNFORGIVEN",
      "FEARLESS",
      "Perfect Night",
      "EASY",
      "Smart",
      "CRAZY",
      "Impurities",
      "Chasing Lightning",
      "Pierrot",
      "HOT",
      "Eve, Psyche & the Bluebeard's wife",
      "Blue Flame",
      "The Hydra",
      "Swan Song",
      "No Return",
    ],
  },
  {
    name: "Ariana Grande",
    songs: [
      "thank u, next",
      "7 rings",
      "positions",
      "34+35",
      "Side to Side",
      "Dangerous Woman",
      "Into You",
      "Problem",
      "Break Free",
      "Bang Bang",
      "Love Me Harder",
      "One Last Time",
      "Focus",
      "Right There",
      "Best Mistake",
      "No Tears Left to Cry",
      "God Is a Woman",
      "Breathin",
      "R.E.M.",
      "Successful",
      "needy",
      "NASA",
      "break up with your girlfriend, i'm bored",
      "fake smile",
      "ghostin",
      "bloodline",
      "in my head",
      "bad idea",
      "imagine",
      "shut up",
      "motive",
      "off the table",
      "just like magic",
      "nasty",
      "love language",
      "west side",
      "obvious",
      "POV",
      "yes, and?",
      "we can't be friends",
      "supernatural",
      "true story",
      "bye",
      "the boy is mine",
      "imperfect for you",
      "eternal sunshine",
      "ordinary things",
      "don't wanna break up again",
      "intro (end of the world)",
      "i wish i hated you",
      "saturn returns interlude",
      "Honeymoon Avenue",
      "The Way",
      "Tattooed Heart",
      "Daydreamin'",
      "Almost Is Never Enough",
      "Baby I",
      "Piano",
      "Be Alright",
      "Moonlight",
      "Greedy",
      "Touch It",
      "Leave Me Lonely",
      "pete davidson",
    ],
  },
  {
    name: "Beabadoobee",
    songs: [
      "Glue Song",
      "Coffee",
      "Last Day on Earth",
      "Cologne",
      "Disappear",
      "Tired of Talking",
      "Talk",
      "Sun More Often",
      "Take a Bite",
      "See You Soon",
      "He Gets Me So High",
      "Care",
      "The Way Things Go",
      "Beaches",
      "10:36",
      "Worth It",
    ],
  },
  {
    name: "Stray Kids",
    songs: [
      "Hellevator",
      "District 9",
      "My Pace",
      "Voices",
      "I Am YOU",
      "Get Cool",
      "Miroh",
      "Victory Song",
      "Side Effects",
      "Double Knot",
      "Levanter",
      "God's Menu",
      "Back Door",
      "Easy",
      "Blueprint",
      "The Tortoise and the Hare",
      "Thunderous",
      "DOMINO",
      "Silent Cry",
      "Red Lights",
      "Christmas EveL",
      "MANIAC",
      "Charmer",
      "VENOM",
      "Lonely St.",
      "Case 143",
      "Taste",
      "S-Class",
      "Topline",
      "Hall of Fame",
      "LALALALA",
      "Chk Chk Boom",
    ],
  },
  {
    name: "aespa",
    songs: [
      "Black Mamba",
      "Next Level",
      "Savage",
      "Girls",
      "Spicy",
      "Drama",
      "Supernova",
      "Armageddon",
      "Whiplash",
      "Dirty Work",
      "Set the Tone",
      "Forever",
      "Illusion",
      "Welcome to MY World",
      "I'm Unhappy",
      "Mine",
    ],
  },
  {
    name: "KATSEYE",
    songs: [
      "Touch",
      "Run for It",
      "Gnarly",
      "Gabriela",
      "Beautiful Chaos",
      "Tonight I Might",
      "Gameboy",
      "Mean Girls",
      "Debut",
      "Crybaby",
      "Soft",
      "Big Bag",
      "Flash",
      "M.I.A",
      "Sis Pause",
      "Tier 1",
    ],
  },
  {
    name: "PARTYNEXTDOOR",
    songs: [
      "Loyal",
      "Recognize",
      "Wus Good / Curious",
      "Persian Rugs",
      "Come and See Me",
      "Not Nice",
      "Don't Run",
      "Right Now",
      "Sex on the Beach",
      "Welcome to the Party",
      "Resentment",
      "Wishing Well",
      "Diamonds",
      "Damage",
      "Bromance",
      "Better",
      "One Time",
      "Make a Mil",
      "Real Woman",
      "Best Friends",
      "Lord Knows",
      "Belong to the City",
      "Spiteful",
      "The Way Out",
      "Picking Up",
      "Late at Night",
      "1942",
      "Loyal Pt. 2",
      "Splash",
      "Brown Skin",
      "Her Way",
      "Northside",
    ],
  },
];

export function getArtist(name: string) {
  return ARTISTS.find((a) => a.name === name);
}
