export type ArtistKey = string;

export const ARTISTS: { name: ArtistKey; songs: string[] }[] = [
  {
    name: "Kanye West",
    songs: [
      "Runaway",
      "Stronger",
      "Power",
      "Gold Digger",
      "All of the Lights",
      "Heartless",
      "Jesus Walks",
      "Flashing Lights",
      "Bound 2",
      "Can't Tell Me Nothing",
      "Black Skinhead",
      "Ultralight Beam",
      "Through the Wire",
      "Devil in a New Dress",
      "Touch the Sky",
      "Father Stretch My Hands Pt. 1",
      "Famous",
      "Good Life",
      "Love Lockdown",
      "All Falls Down",
      "Monster",
      "Dark Fantasy",
      "Blood on the Leaves",
      "Waves",
      "Hey Mama",
      "Homecoming",
      "Diamonds from Sierra Leone",
      "Gorgeous",
      "Slow Jamz",
      "Champion",
      "New Slaves",
      "Street Lights",
      "Spaceship",
      "We Don't Care",
      "Family Business",
      "Saint Pablo",
      "Real Friends",
      "Welcome to Heartbreak",
      "Wolves",
      "FML",
      "Hell of a Life",
      "Lost in the World",
      "I Wonder",
      "Roses",
      "Late",
      "Get 'Em High",
      "School Spirit",
      "Two Words",
      "Ghost Town",
      "Violent Crimes",
      "Hurricane",
      "Jesus Lord",
      "Off the Grid",
      "Jail",
      "24",
      "Believe What I Say",
      "Praise God",
      "Moon",
      "Carnival",
      "Good Morning",
      "Robocop",
      "Amazing",
      "Paranoid",
      "Coldest Winter",
    ],
  },
  {
    name: "Drake",
    songs: [
      "Marvins Room",
      "Hotline Bling",
      "God's Plan",
      "Passionfruit",
      "Take Care",
      "Headlines",
      "Started From the Bottom",
      "Nonstop",
      "One Dance",
      "Energy",
      "Jungle",
      "Hold On, We're Going Home",
      "0 to 100 / The Catch Up",
      "Forever",
      "Best I Ever Had",
      "Over",
      "Find Your Love",
      "The Motto",
      "Worst Behavior",
      "Trophies",
      "Pound Cake / Paris Morton Music 2",
      "From Time",
      "Furthest Thing",
      "Too Much",
      "Know Yourself",
      "5AM in Toronto",
      "Crew Love",
      "Fancy",
      "Successful",
      "Fireworks",
      "Shot for Me",
      "Doing It Wrong",
      "Look What You've Done",
      "Practice",
      "The Ride",
      "Lord Knows",
      "HYFR (Hell Ya Fuckin' Right)",
      "Make Me Proud",
      "Cameras",
      "Controlla",
      "Feel No Ways",
      "Fake Love",
      "Child's Play",
      "Redemption",
      "Back to Back",
      "Charged Up",
      "Summer Sixteen",
      "Jumpman",
      "Big Rings",
      "Portland",
      "Free Smoke",
      "Sticky",
      "Nice for What",
      "In My Feelings",
      "Laugh Now Cry Later",
      "Toosie Slide",
      "Chicago Freestyle",
      "Teenage Fever",
      "Champagne Poetry",
      "First Person Shooter",
      "Rich Baby Daddy",
      "Nokia",
      "Gimme a Hug",
      "Views",
    ],
  },
  {
    name: "Travis Scott",
    songs: [
      "SICKO MODE",
      "goosebumps",
      "STARGAZING",
      "ANTIDOTE",
      "HIGHEST IN THE ROOM",
      "90210",
      "BUTTERFLY EFFECT",
      "FE!N",
      "CAROUSEL",
      "NO BYSTANDERS",
      "R.I.P. SCREW",
      "SKELETONS",
      "STOP TRYING TO BE GOD",
      "ASTROTHUNDER",
      "NC-17",
      "WAKE UP",
      "COFFEE BEAN",
      "MELTDOWN",
      "MY EYES",
      "HYAENA",
      "I KNOW ?",
      "TELEKINESIS",
      "MODERN JAM",
      "CIRCUS MAXIMUS",
      "3500",
      "Maria I'm Drunk",
      "Oh My Dis Side",
      "Pornography",
      "Wasted",
      "Nightcrawler",
      "Piss On Your Grave",
      "Impossible",
      "Apple Pie",
      "Pray 4 Love",
      "beibs in the trap",
      "through the late night",
      "way back",
      "coordinate",
      "first take",
      "sweet sweet",
      "wonderful",
      "Drugs You Should Try It",
      "Mamacita",
      "Upper Echelon",
      "Don't Play",
      "Quintana",
      "SDP Interlude",
      "Houstonfornication",
      "YOSEMITE",
      "Can't Say",
      "Who? What!",
      "THANK GOD",
      "TOPIA TWINS",
      "PARASAIL",
      "DELRESTO (ECHOES)",
      "LOST FOREVER",
      "K-POP",
      "GOD'S COUNTRY",
      "LOOOVE",
      "TIL FURTHER NOTICE",
      "GATTI",
      "OUT WEST",
      "WHAT TO DO?",
      "ESCAPE PLAN",
    ],
  },
  {
    name: "Frank Ocean",
    songs: [
      "Thinkin Bout You",
      "Pink + White",
      "Self Control",
      "Nights",
      "Ivy",
      "Pyramids",
      "Nikes",
      "White Ferrari",
      "Bad Religion",
      "Super Rich Kids",
      "Lost",
      "Solo",
      "Godspeed",
      "Sweet Life",
      "Pink Matter",
      "Seigfried",
      "Chanel",
      "Novacane",
      "Forrest Gump",
      "Crack Rock",
      "Sierra Leone",
      "Pilot Jones",
      "Skyline To",
      "Be Yourself",
      "Good Guy",
      "Solo (Reprise)",
      "Futura Free",
      "Close to You",
      "Swim Good",
      "Strawberry Swing",
      "We All Try",
      "Lovecrimes",
      "Songs for Women",
      "There Will Be Tears",
      "Dust",
      "Nature Feels",
      "American Wedding",
      "Soul Calibur",
      "Provider",
      "Biking",
      "Lens",
      "DHL",
      "In My Room",
      "Cayendo",
      "Dear April",
      "Moon River",
      "At Your Best (You Are Love)",
      "Slide On Me",
      "Wither",
      "Comme des Garçons",
      "U-N-I-T-Y",
      "Higgs",
      "Rushes",
      "Rushes To",
      "Florida",
      "Mine",
      "Wiseman (unreleased)",
      "Voodoo (unreleased)",
      "Orion (unreleased)",
      "Bedtime Stories (unreleased)",
      "Trouble (unreleased)",
      "Coral (ft. Bon Iver) (leaked)",
      "Spaceman (leaked demo)",
      "Memrise (unreleased)",
    ],
  },
  {
    name: "Daniel Caesar",
    songs: [
      "Best Part (ft. H.E.R.)",
      "Get You (ft. Kali Uchis)",
      "Japanese Denim",
      "Blessed",
      "Always",
      "Hold Me Down",
      "Superpowers",
      "Loose",
      "We Find Love",
      "Neu Roses (Transgressor's Song)",
      "Take Me Away (ft. Syd)",
      "Transform (ft. Charlotte Day Wilson)",
      "Freudian",
      "CYANIDE",
      "SUPERPOSITION (ft. John Mayer)",
      "LOVE AGAIN (ft. Brandy)",
      "ENTROPY",
      "FRONTAL LOBE MUZIK (ft. Pharrell Williams)",
      "OPEN UP",
      "RESTORE THE FEELING",
      "TOO DEEP TO TURN BACK",
      "ARE YOU OK?",
      "COMPLEXITIES",
      "Ocho Rios",
      "Valentina",
      "Toronto 2014",
      "Disillusioned",
      "Cool",
      "Vince Van Gogh",
      "Pain Is Inevitable",
      "Let Me Go",
      "Buyer's Remorse",
      "Unstoppable",
      "Shot My Baby",
      "Homiesexual (ft. Ty Dolla $ign)",
      "Do You Like Me?",
      "Rain Down (ft. Sampha)",
      "Moon (ft. Bon Iver)",
      "Have a Baby (With Me)",
      "Call on Me",
      "Who Knows",
      "Baby Blue (ft. Norwill Simmonds)",
      "Touching God (ft. Blood Orange & Yebba)",
      "No More Loving (On Women I Don't Love) (ft. 646YF4T)",
      "Root of All Evil",
      "Sign of the Times",
      "Emily's Song",
      "Sins of the Father (ft. Bon Iver)",
      "Peaches (Justin Bieber, ft. Daniel Caesar & Giveon)",
      "Please Do Not Lean (ft. BADBADNOTGOOD)",
      "Waiting in Vain",
      "CYANIDE Remix (ft. Koffee)",
      "Rearrange My World (w/ Rex Orange County)",
      "There's a Field (That's Only Yours) (w/ Rex Orange County)",
      "Won't Live Here",
      "Death & Taxes",
      "Streetcar",
      "Pseudo",
      "Violet",
      "We'll Always Have Paris",
      "Hold On",
      "Beauty & Essex (Free Nationals, ft. Daniel Caesar & UMO)",
      "Chevalier",
      "Birthday (unreleased)",
    ],
  },
  {
    name: "The Weeknd",
    songs: [
      "Blinding Lights",
      "Starboy",
      "The Hills",
      "Can't Feel My Face",
      "Often",
      "Earned It",
      "House of Balloons / Glass Table Girls",
      "Wicked Games",
      "The Morning",
      "High for This",
      "Save Your Tears",
      "Call Out My Name",
      "I Feel It Coming",
      "Die for You",
      "Heartless",
      "In Your Eyes",
      "Pray for Me (w/ Kendrick Lamar)",
      "Acquainted",
      "Reminder",
      "Tell Your Friends",
      "The Knowing",
      "Love Me Harder (w/ Ariana Grande)",
      "Party Monster",
      "Sidewalks",
      "Secrets",
      "Real Life",
      "As You Are",
      "The Birds Pt. 1",
      "The Birds Pt. 2",
      "Twenty Eight",
      "Initiation",
      "Wanderlust",
      "Belong to the World",
      "Kiss Land",
      "Live For (ft. Drake)",
      "Tears in the Rain",
      "Pretty",
      "Adaptation",
      "Loft Music",
      "Coming Down",
      "What You Need",
      "Gone",
      "Rolling Stone",
      "The Zone (ft. Drake)",
      "Lonely Star",
      "Outside",
      "São Paulo (ft. Anitta)",
      "XO / The Host",
      "Montreal",
      "Hardest to Love",
      "Try Me",
      "Privilege",
      "After Hours",
      "Snowchild",
      "Alone Again",
      "Too Late",
      "Open Hearts",
      "Scared to Live",
      "Faith",
      "Take My Breath",
      "Sacrifice",
      "Out of Time",
      "Less Than Zero",
      "Timeless (w/ Playboi Carti)",
    ],
  },
  {
    name: "Bad Bunny",
    songs: [
      "Tití Me Preguntó",
      "Yonaguni",
      "DÁKITI (w/ Jhayco)",
      "Me Porto Bonito (w/ Chencho Corleone)",
      "Callaíta",
      "Moscow Mule",
      "Vete",
      "Safaera (w/ Jowell & Randy, Ñengo Flow)",
      "La Difícil",
      "BAILE INoLVIDABLE",
      "Soy Peor",
      "Ojitos Lindos (w/ Bomba Estéreo)",
      "Yo Perreo Sola",
      "MIA (ft. Drake)",
      "Después de la Playa",
      "DtMF",
      "Efecto",
      "NUEVAYoL",
      "Estamos Bien",
      "La Canción (w/ J Balvin)",
      "Un x100to (w/ Grupo Frontera)",
      "Neverita",
      "La Romana (w/ El Alfa)",
      "200 MPH (w/ Diplo)",
      "Diles",
      "Amorfoda",
      "El Apagón",
      "Caro",
      "Tenemos Que Hablar",
      "Si Veo a Tu Mamá",
      "La Santa (w/ Daddy Yankee)",
      "25/8",
      "Booker T",
      "Bichiyal (w/ Yaviah)",
      "PERFuMITO NUEVO (w/ RaiNao)",
      "La Mudanza",
      "Pero Ya No",
      "Solo de Mí",
      "Otra Noche en Miami",
      "Where She Goes",
      "Mónaco",
      "EoO",
      "VeLDÁ (w/ Omar Courtz, Dei V)",
      "Mojabi Ghost (w/ Tainy)",
      "Está Cabrón Ser Yo",
      "Pitorro de Coco",
      "Acho PR (w/ Arcángel, De La Ghetto, Ñengo Flow)",
      "Voy a Llevarte pa PR",
      "Andrea (w/ Buscabulla)",
      "Como Antes",
      "Ignorantes (w/ Sech)",
      "Yo No Soy Celoso",
      "Hablamos Mañana",
      "El Clúb",
      "Cybertruck",
      "Una Velita",
      "Café con Ron (w/ Los Pleneros de la Cresta)",
      "Weltita (w/ Chuwi)",
      "Turista",
      "Bokete",
      "Lo Que Le Pasó a Hawaii",
      "Tarot (w/ Jhayco)",
      "Party (w/ Rauw Alejandro)",
      "Hoy Cobré",
    ],
  },
  {
    name: "Kendrick Lamar",
    songs: [
      "HUMBLE.",
      "Alright",
      "Money Trees",
      "Swimming Pools (Drank)",
      "King Kunta",
      "m.A.A.d city",
      "Bitch, Don't Kill My Vibe",
      "DNA.",
      "Not Like Us",
      "Backseat Freestyle",
      "The Art of Peer Pressure",
      "Sing About Me, I'm Dying of Thirst",
      "Poetic Justice",
      "Good Kid",
      "ELEMENT.",
      "LOYALTY.",
      "LOVE.",
      "All the Stars",
      "These Walls",
      "i",
      "The Blacker the Berry",
      "Wesley's Theory",
      "How Much a Dollar Cost",
      "u",
      "For Free? (Interlude)",
      "Institutionalized",
      "Hood Politics",
      "Complexion (A Zulu Love)",
      "Mortal Man",
      "FEAR.",
      "PRIDE.",
      "XXX.",
      "FEEL.",
      "DUCKWORTH.",
      "YAH.",
      "LUST.",
      "GOD.",
      "BLOOD.",
      "Euphoria",
      "meet the grahams",
      "6:16 in LA",
      "squabble up",
      "tv off",
      "luther",
      "wacced out murals",
      "reincarnated",
      "peekaboo",
      "man at the garden",
      "gnx",
      "dodger blue",
      "hey now",
      "gloria",
      "heart pt. 6",
      "Like That",
      "ADHD",
      "Cartoon & Cereal",
      "HiiiPoWeR",
      "Rigamortus",
      "The Recipe",
      "Count Me Out",
      "N95",
      "Father Time",
      "United in Grief",
      "Auntie Diaries",
    ],
  },
  {
    name: "SZA",
    songs: [
      "Kill Bill",
      "Snooze",
      "Good Days",
      "The Weekend",
      "Love Galore",
      "Drew Barrymore",
      "Broken Clocks",
      "Supermodel",
      "Nobody Gets Me",
      "Shirt",
      "Doves in the Wind",
      "Prom",
      "Garden (Say It Like Dat)",
      "Go Gina",
      "Normal Girl",
      "20 Something",
      "Anything",
      "Pretty Little Birds",
      "I Hate U",
      "Open Arms",
      "Special",
      "Blind",
      "Low",
      "Smoking on My Ex Pack",
      "Ghost in the Machine",
      "F2F",
      "SOS",
      "Seek & Destroy",
      "Love Language",
      "Gone Girl",
      "Used",
      "Notice Me",
      "Conceited",
      "Too Late",
      "Far",
      "Forgiveless",
      "Saturn",
      "Drive",
      "BMF",
      "30 for 30",
      "PSA",
      "Crybaby",
      "Joni",
      "Diamond Boy",
      "Another Life",
      "My Turn",
      "Scorsese Baby Daddy",
      "Chill Baby",
      "Get Behind Me",
      "What Do I Do",
      "Hit Different",
      "Power Is Power",
      "Babylon",
      "Childs Play",
      "Sweet November",
      "Julia",
      "Warm Winds",
      "Green Mile",
      "2AM",
      "Miles",
      "Tread Carefully",
      "The Other Side",
      "Kiss Me More",
      "Consideration",
    ],
  },
  {
    name: "Tyler, the Creator",
    songs: [
      "EARFQUAKE",
      "See You Again",
      "Yonkers",
      "NEW MAGIC WAND",
      "Who Dat Boy",
      "IFHY",
      "911 / Mr. Lonely",
      "Boredom",
      "WUSYANAME",
      "RUNNING OUT OF TIME",
      "ARE WE STILL FRIENDS?",
      "Sticky",
      "Noid",
      "GONE, GONE / THANK YOU",
      "I THINK",
      "Garden Shed",
      "SMUCKERS",
      "She",
      "PUPPET",
      "A BOY IS A GUN*",
      "Where This Flower Blooms",
      "Foreword",
      "November",
      "Glitter",
      "LEMONHEAD",
      "SWEET / I THOUGHT YOU WANTED TO DANCE",
      "MASSA",
      "CORSO",
      "LUMBERJACK",
      "HOT WIND BLOWS",
      "JUGGERNAUT",
      "RISE!",
      "St. Chroma",
      "Rah Tah Tah",
      "Darling, I",
      "Hey Jane",
      "Take Your Mask Off",
      "Like Him",
      "Thought I Was Dead",
      "Judge Judy",
      "Balloon",
      "Tomorrow",
      "I Killed You",
      "Big Poe",
      "Sugar on My Tongue",
      "Ring Ring Ring",
      "Sucka Free",
      "Mommanem",
      "Stop Playing With Me",
      "Don't Tap That Glass / Tweakin'",
      "Don't You Worry Baby",
      "Tamale",
      "Domo23",
      "Bimmer",
      "F**king Young / Perfect",
      "DEATHCAMP",
      "CHERRY BOMB",
      "Cowboy",
      "Awkward",
      "48",
      "Answer",
      "Pigs",
      "OKRA",
      "GROUP B",
    ],
  },
  {
    name: "Kid Cudi",
    songs: [
      "Day 'n' Nite",
      "Pursuit of Happiness",
      "Soundtrack 2 My Life",
      "Mr. Rager",
      "Erase Me",
      "Reborn",
      "Cudi Zone",
      "Up Up & Away",
      "Make Her Say",
      "Sky Might Fall",
      "Heart of a Lion (Kid Cudi Theme Music)",
      "Marijuana",
      "Mojo So Dope",
      "REVOFEV",
      "GHOST!",
      "Trapped in My Mind",
      "Don't Play This Song",
      "These Worries",
      "All Along",
      "Maniac",
      "Scott Mescudi vs. the World",
      "The End",
      "Enter Galactic (Love Connection, Pt. 1)",
      "My World",
      "Solo Dolo (Nightmare)",
      "Alive",
      "Just What I Am",
      "Immortal",
      "King Wizard",
      "Unfuckwittable",
      "Brothers",
      "Beez",
      "Cold Blooded",
      "Internal Bleeding",
      "Going to the Ceremony",
      "Satellite Flight",
      "Surfin'",
      "Frequency",
      "Baptized in Fire",
      "Feel the Love",
      "4th Dimension",
      "Fire",
      "Cudi Montage",
      "Kids See Ghosts",
      "Freeee (Ghost Town, Pt. 2)",
      "Tequila Shots",
      "She Knows This",
      "Heaven on Earth",
      "The Void",
      "Show Out",
      "Mr. Solo Dolo III",
      "Sad People",
      "Leader of the Delinquents",
      "Dive",
      "Damaged",
      "Lovin' Me",
      "Sept. 16",
      "Willing to Trust",
      "Angel",
      "Pillow Talk",
      "Ashin' Kusher",
      "Down & Out",
      "Confused!",
      "Do What I Want",
    ],
  },
  {
    name: "Playboi Carti",
    songs: [
      "Magnolia",
      "Sky",
      "Shoota",
      "Long Time (Intro)",
      "R.I.P.",
      "wokeuplikethis*",
      "Location",
      "Love Hurts",
      "dothatshit!",
      "New Tank",
      "Stop Breathing",
      "Rockstar Made",
      "Vamp Anthem",
      "Go2DaMoon",
      "Fell In Luv",
      "Poke It Out",
      "Right Now",
      "Lean 4 Real",
      "Slay3r",
      "ILoveUIHateU",
      "M3tamorphosis",
      "Place",
      "King Vamp",
      "Teen X",
      "Beno!",
      "JumpOutTheHouse",
      "No Sl33p",
      "Control",
      "Over",
      "Die4Guy",
      "New N3on",
      "Punk Monk",
      "On That Time",
      "Foreign",
      "Pull Up",
      "Home (KOD)",
      "Old Money",
      "Mileage",
      "Choppa Won't Miss",
      "No Time",
      "FlatBed Freestyle",
      "Middle of the Summer",
      "Top",
      "Kelly K",
      "Half & Half",
      "NO. 9",
      "Let It Go",
      "Other Shit",
      "Yah Mean",
      "POP OUT",
      "EVIL J0RDAN",
      "K POP",
      "CRUSH",
      "MOJO JOJO",
      "RATHER LIE",
      "BACKD00R",
      "FINE SHIT",
      "TOXIC",
      "CHARGE DEM HOES A FEE",
      "GOOD CREDIT",
      "WALK",
      "MUNYUN",
      "WAKE UP F1LTHY",
      "LIKE WEEZY",
    ],
  },
  {
    name: "Lil Uzi Vert",
    songs: [
      "XO TOUR Llif3",
      "Money Longer",
      "The Way Life Goes",
      "Just Wanna Rock",
      "20 Min",
      "You Was Right",
      "Do What I Want",
      "Sauce It Up",
      "Erase Your Social",
      "Neon Guts",
      "P2",
      "Baby Pluto",
      "Lo Mein",
      "Silly Watch",
      "Celebration Station",
      "Pop",
      "Prices",
      "Bean (Kobe)",
      "Wassup",
      "That Way",
      "Homecoming",
      "Bigger Than Life",
      "Sideline Watching (Hold Up)",
      "Ps & Qs",
      "7AM",
      "Money Mitch",
      "Of Course We Ghetto Flowers",
      "Canadian Goose",
      "Scott and Ramona",
      "Futsal Shuffle 2020",
      "Sasuke",
      "Endless Fashion",
      "Flooded the Face",
      "Aye",
      "CS",
      "Spaceship",
      "Suicide Doors",
      "Werewolf",
      "Patience",
      "Days Come and Go",
      "Demon High",
      "Chrome Heart Tags",
      "Nakamura",
      "Glock in My Purse",
      "Pluto to Mars",
      "Sanguine Paradise",
      "Free Uzi",
      "Strawberry Peels",
      "Lotus",
      "Venetia",
      "Urgency",
      "Bust Me",
      "How to Talk",
      "Dark Queen",
      "Luv Scars",
      "Amped",
      "Zoom",
      "Hectic",
      "Came Up",
      "Mama, I'm Sorry",
      "Heavy Metal",
      "All Alone",
      "x2",
      "Died and Came Back",
    ],
  },
  {
    name: "Lana Del Rey",
    songs: [
      "Video Games",
      "Summertime Sadness",
      "Born to Die",
      "Young and Beautiful",
      "Blue Jeans",
      "West Coast",
      "Off to the Races",
      "Ride",
      "Norman fucking Rockwell",
      "Venice Bitch",
      "Doin' Time",
      "Mariners Apartment Complex",
      "Cinnamon Girl",
      "The greatest",
      "National Anthem",
      "Cola",
      "Shades of Cool",
      "Brooklyn Baby",
      "Ultraviolence",
      "Pretty When You Cry",
      "Sad Girl",
      "Old Money",
      "Dark Paradise",
      "Million Dollar Man",
      "Gods & Monsters",
      "Diet Mountain Dew",
      "Radio",
      "Carmen",
      "This Is What Makes Us Girls",
      "Lust for Life",
      "Love",
      "White Mustang",
      "Get Free",
      "13 Beaches",
      "Cherry",
      "High by the Beach",
      "Music to Watch Boys To",
      "Honeymoon",
      "Terrence Loves You",
      "Salvatore",
      "Religion",
      "Freak",
      "Art Deco",
      "Hope Is a Dangerous Thing for a Woman Like Me to Have - but I Have It",
      "Fuck It I Love You",
      "Bartender",
      "The Next Best American Record",
      "How to Disappear",
      "California",
      "Love Song",
      "Chemtrails over the Country Club",
      "White Dress",
      "Tulsa Jesus Freak",
      "Wild at Heart",
      "Arcadia",
      "Blue Banisters",
      "A&W",
      "Did You Know That There's a Tunnel Under Ocean Blvd",
      "The Grants",
      "Margaret",
      "Let the Light In",
      "Henry, Come On",
      "Bluebird",
      "Yes to Heaven",
    ],
  },
  {
    name: "Billie Eilish",
    songs: [
      "bad guy",
      "Birds of a Feather",
      "Happier Than Ever",
      "when the party's over",
      "everything i wanted",
      "ocean eyes",
      "bury a friend",
      "lovely",
      "Wildflower",
      "What Was I Made For?",
      "Lunch",
      "you should see me in a crown",
      "Therefore I Am",
      "Your Power",
      "ilomilo",
      "NDA",
      "my future",
      "Chihiro",
      "Skinny",
      "The Greatest",
      "Bellyache",
      "idontwannabeyouanymore",
      "Copycat",
      "Party Favor",
      "Watch",
      "My Boy",
      "xanny",
      "wish you were gay",
      "all the good girls go to hell",
      "my strange addiction",
      "8",
      "listen before i go",
      "i love you",
      "goodbye",
      "!!!!!!!",
      "Getting Older",
      "I Didn't Change My Number",
      "Billie Bossa Nova",
      "Oxytocin",
      "GOLDWING",
      "Lost Cause",
      "Halley's Comet",
      "Everybody Dies",
      "OverHeated",
      "Male Fantasy",
      "Not My Responsibility",
      "L'Amour de Ma Vie",
      "The Diner",
      "Bittersuite",
      "Blue",
      "No Time to Die",
      "Guess",
      "Never Felt So Alone",
      "Six Feet Under",
      "Bored",
      "Come Out and Play",
      "Hostage",
      "&Burn",
      "when i was older",
      "TV",
      "The 30th",
      "Lo Vas a Olvidar",
      "bitches broken hearts",
      "Fingers Crossed",
    ],
  },
  {
    name: "Tame Impala",
    songs: [
      "The Less I Know the Better",
      "Let It Happen",
      "Feels Like We Only Go Backwards",
      "Elephant",
      "New Person, Same Old Mistakes",
      "Eventually",
      "Borderline",
      "Lost in Yesterday",
      "The Moment",
      "Why Won't They Talk to Me?",
      "'Cause I'm a Man",
      "Yes I'm Changing",
      "Apocalypse Dreams",
      "Mind Mischief",
      "Solitude Is Bliss",
      "Why Won't You Make Up Your Mind?",
      "Alter Ego",
      "Endors Toi",
      "It Is Not Meant to Be",
      "Lucidity",
      "Desire Be Desire Go",
      "Half Full Glass of Wine",
      "Expectation",
      "Runway, Houses, City, Clouds",
      "Nangs",
      "The Bold Arrow of Time",
      "Music to Walk Home By",
      "Keep on Lying",
      "Be Above It",
      "Posthumous Forgiveness",
      "Breathe Deeper",
      "Is It True",
      "Tomorrow's Dust",
      "On Track",
      "One More Year",
      "Instant Destiny",
      "It Might Be Time",
      "Patience",
      "Sundown Syndrome",
      "List of People (To Try and Forget About)",
      "Powerlines",
      "Taxi's Here",
      "Disciples",
      "Reality in Motion",
      "Love/Paranoia",
      "Past Life",
      "Gossip",
      "Sun's Coming Up",
      "Nothing That Has Happened So Far Has Been Anything We Could Control",
      "I Don't Really Mind",
      "Jeremy's Storm",
      "She Just Won't Believe Me",
      "Glimmer",
      "One More Hour",
      "Dracula",
      "Loser",
      "End of Summer",
      "My Old Ways",
      "Oblivion",
      "No Reply",
      "Not My World",
      "Piece of Heaven",
      "Obsolete",
      "Afterthought",
    ],
  },
];

export function getArtist(name: string) {
  return ARTISTS.find((a) => a.name === name);
}
